2022-07-19 23:27:36,924:INFO:PyCaret Supervised Module
2022-07-19 23:27:36,924:INFO:ML Usecase: regression
2022-07-19 23:27:36,930:INFO:version 2.2.2
2022-07-19 23:27:36,930:INFO:Initializing setup()
2022-07-19 23:27:36,930:INFO:setup(target=Attrition, ml_usecase=regression, available_plots={'parameter': 'Hyperparameters', 'residuals': 'Residuals', 'error': 'Prediction Error', 'cooks': 'Cooks Distance', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'vc': 'Validation Curve', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'tree': 'Decision Tree'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=kfold, fold=10, fold_shuffle=False, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=None, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2022-07-19 23:27:36,930:INFO:Checking environment
2022-07-19 23:27:36,930:INFO:python_version: 3.9.7
2022-07-19 23:27:36,930:INFO:python_build: ('default', 'Sep 16 2021 08:50:36')
2022-07-19 23:27:36,930:INFO:machine: x86_64
2022-07-19 23:27:36,930:INFO:platform: macOS-10.16-x86_64-i386-64bit
2022-07-19 23:27:36,931:INFO:Memory: svmem(total=17179869184, available=830869504, percent=95.2, used=1308426240, free=19742720, active=815214592, inactive=805834752, wired=493211648)
2022-07-19 23:27:36,931:INFO:Physical Core: 8
2022-07-19 23:27:36,931:INFO:Logical Core: 8
2022-07-19 23:27:36,931:INFO:Checking libraries
2022-07-19 23:27:36,931:INFO:pd==1.4.2
2022-07-19 23:27:36,931:INFO:numpy==1.21.5
2022-07-19 23:27:36,931:INFO:sklearn==0.23.2
2022-07-19 23:27:37,036:INFO:xgboost==1.5.2
2022-07-19 23:27:37,036:INFO:lightgbm==3.3.2
2022-07-19 23:27:37,087:INFO:catboost==1.0.4
2022-07-19 23:27:37,329:INFO:mlflow==1.24.0
2022-07-19 23:27:37,329:INFO:Checking Exceptions
2022-07-19 23:27:37,329:INFO:Declaring global variables
2022-07-19 23:27:37,329:INFO:USI: acb7
2022-07-19 23:27:37,329:INFO:pycaret_globals: {'_all_models_internal', 'fold_param', 'y_train', 'imputation_classifier', 'fix_imbalance_param', 'target_param', 'n_jobs_param', 'y_test', 'gpu_param', 'log_plots_param', 'prep_pipe', 'imputation_regressor', 'logging_param', 'exp_name_log', 'seed', '_ml_usecase', 'fold_generator', 'master_model_container', 'pycaret_globals', 'stratify_param', 'X_train', 'fold_shuffle_param', 'y', 'display_container', 'create_model_container', 'data_before_preprocess', '_all_metrics', 'X', 'X_test', 'experiment__', 'fix_imbalance_method_param', '_available_plots', 'iterative_imputation_iters_param', 'transform_target_param', 'transform_target_method_param', 'USI', 'html_param', 'fold_groups_param', '_all_models', '_internal_pipeline', '_gpu_n_jobs_param'}
2022-07-19 23:27:37,329:INFO:Preparing display monitor
2022-07-19 23:27:37,329:INFO:Preparing display monitor
2022-07-19 23:27:37,336:INFO:Importing libraries
2022-07-19 23:27:37,337:INFO:Copying data for preprocessing
2022-07-19 23:27:37,341:INFO:Declaring preprocessing parameters
2022-07-19 23:27:37,345:INFO:Creating preprocessing pipeline
2022-07-19 23:27:37,357:INFO:Preprocessing pipeline created successfully
2022-07-19 23:27:37,358:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2022-07-19 23:27:37,358:INFO:Creating global containers
2022-07-19 23:27:37,359:INFO:Internal pipeline: Pipeline(memory=None, steps=[('empty_step', 'passthrough')], verbose=False)
2022-07-19 23:27:39,911:INFO:Creating grid variables
2022-07-19 23:27:39,922:INFO:create_model_container: 0
2022-07-19 23:27:39,922:INFO:master_model_container: 0
2022-07-19 23:27:39,922:INFO:display_container: 0
2022-07-19 23:27:39,925:INFO:Pipeline(memory=None,
         steps=[('dtypes',
                 DataTypes_Auto_infer(categorical_features=[],
                                      display_types=True, features_todrop=[],
                                      id_columns=[],
                                      ml_usecase='classification',
                                      numerical_features=[], target='Attrition',
                                      time_features=[])),
                ('imputer',
                 Simple_Imputer(categorical_strategy='not_available',
                                fill_value_categorical=None,
                                fill_value_numerical=None,
                                numeric_st...
                ('scaling', 'passthrough'), ('P_transform', 'passthrough'),
                ('binn', 'passthrough'), ('rem_outliers', 'passthrough'),
                ('cluster_all', 'passthrough'),
                ('dummy', Dummify(target='Attrition')),
                ('fix_perfect', Remove_100(target='Attrition')),
                ('clean_names', Clean_Colum_Names()),
                ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                ('dfs', 'passthrough'), ('pca', 'passthrough')],
         verbose=False)
2022-07-19 23:27:39,925:INFO:setup() succesfully completed......................................
2022-07-19 23:28:37,311:INFO:Initializing compare_models()
2022-07-19 23:28:37,312:INFO:compare_models(include=None, fold=None, round=4, cross_validation=True, sort=R2, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, verbose=True, display=None, exclude=None)
2022-07-19 23:28:37,312:INFO:Checking exceptions
2022-07-19 23:28:37,312:INFO:Preparing display monitor
2022-07-19 23:28:37,314:INFO:Preparing display monitor
2022-07-19 23:28:37,352:INFO:Initializing Linear Regression
2022-07-19 23:28:37,352:INFO:Total runtime is 2.4159749348958332e-06 minutes
2022-07-19 23:28:37,357:INFO:SubProcess create_model() called ==================================
2022-07-19 23:28:37,358:INFO:Initializing create_model()
2022-07-19 23:28:37,358:INFO:create_model(estimator=lr, fold=KFold(n_splits=10, random_state=4755, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdbda142430>, kwargs={})
2022-07-19 23:28:37,358:INFO:Checking exceptions
2022-07-19 23:28:37,358:INFO:Importing libraries
2022-07-19 23:28:37,358:INFO:Copying training dataset
2022-07-19 23:28:37,359:INFO:Defining folds
2022-07-19 23:28:37,359:INFO:Declaring metric variables
2022-07-19 23:28:37,363:INFO:Importing untrained model
2022-07-19 23:28:37,368:INFO:Linear Regression Imported succesfully
2022-07-19 23:28:37,377:INFO:Starting cross validation
2022-07-19 23:28:37,382:INFO:Cross validating with KFold(n_splits=10, random_state=4755, shuffle=False), n_jobs=-1
2022-07-19 23:28:40,254:INFO:Calculating mean and std
2022-07-19 23:28:40,257:INFO:Creating metrics dataframe
2022-07-19 23:28:40,305:INFO:Uploading results into container
2022-07-19 23:28:40,305:INFO:Uploading model into container now
2022-07-19 23:28:40,305:INFO:create_model_container: 1
2022-07-19 23:28:40,306:INFO:master_model_container: 1
2022-07-19 23:28:40,306:INFO:display_container: 1
2022-07-19 23:28:40,306:INFO:LinearRegression(copy_X=True, fit_intercept=True, n_jobs=-1, normalize=False)
2022-07-19 23:28:40,306:INFO:create_model() succesfully completed......................................
2022-07-19 23:28:40,415:INFO:SubProcess create_model() end ==================================
2022-07-19 23:28:40,415:INFO:Creating metrics dataframe
2022-07-19 23:28:40,432:INFO:Initializing Lasso Regression
2022-07-19 23:28:40,432:INFO:Total runtime is 0.05132761796315511 minutes
2022-07-19 23:28:40,438:INFO:SubProcess create_model() called ==================================
2022-07-19 23:28:40,438:INFO:Initializing create_model()
2022-07-19 23:28:40,438:INFO:create_model(estimator=lasso, fold=KFold(n_splits=10, random_state=4755, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdbda142430>, kwargs={})
2022-07-19 23:28:40,438:INFO:Checking exceptions
2022-07-19 23:28:40,438:INFO:Importing libraries
2022-07-19 23:28:40,438:INFO:Copying training dataset
2022-07-19 23:28:40,439:INFO:Defining folds
2022-07-19 23:28:40,440:INFO:Declaring metric variables
2022-07-19 23:28:40,445:INFO:Importing untrained model
2022-07-19 23:28:40,451:INFO:Lasso Regression Imported succesfully
2022-07-19 23:28:40,462:INFO:Starting cross validation
2022-07-19 23:28:40,462:INFO:Cross validating with KFold(n_splits=10, random_state=4755, shuffle=False), n_jobs=-1
2022-07-19 23:28:40,506:INFO:Calculating mean and std
2022-07-19 23:28:40,507:INFO:Creating metrics dataframe
2022-07-19 23:28:40,524:INFO:Uploading results into container
2022-07-19 23:28:40,524:INFO:Uploading model into container now
2022-07-19 23:28:40,524:INFO:create_model_container: 2
2022-07-19 23:28:40,524:INFO:master_model_container: 2
2022-07-19 23:28:40,524:INFO:display_container: 1
2022-07-19 23:28:40,524:INFO:Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=4755,
      selection='cyclic', tol=0.0001, warm_start=False)
2022-07-19 23:28:40,524:INFO:create_model() succesfully completed......................................
2022-07-19 23:28:40,577:INFO:SubProcess create_model() end ==================================
2022-07-19 23:28:40,577:INFO:Creating metrics dataframe
2022-07-19 23:28:40,590:INFO:Initializing Ridge Regression
2022-07-19 23:28:40,590:INFO:Total runtime is 0.053965349992116295 minutes
2022-07-19 23:28:40,595:INFO:SubProcess create_model() called ==================================
2022-07-19 23:28:40,595:INFO:Initializing create_model()
2022-07-19 23:28:40,595:INFO:create_model(estimator=ridge, fold=KFold(n_splits=10, random_state=4755, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdbda142430>, kwargs={})
2022-07-19 23:28:40,595:INFO:Checking exceptions
2022-07-19 23:28:40,595:INFO:Importing libraries
2022-07-19 23:28:40,595:INFO:Copying training dataset
2022-07-19 23:28:40,596:INFO:Defining folds
2022-07-19 23:28:40,596:INFO:Declaring metric variables
2022-07-19 23:28:40,600:INFO:Importing untrained model
2022-07-19 23:28:40,604:INFO:Ridge Regression Imported succesfully
2022-07-19 23:28:40,613:INFO:Starting cross validation
2022-07-19 23:28:40,613:INFO:Cross validating with KFold(n_splits=10, random_state=4755, shuffle=False), n_jobs=-1
2022-07-19 23:28:40,653:INFO:Calculating mean and std
2022-07-19 23:28:40,653:INFO:Creating metrics dataframe
2022-07-19 23:28:40,669:INFO:Uploading results into container
2022-07-19 23:28:40,669:INFO:Uploading model into container now
2022-07-19 23:28:40,669:INFO:create_model_container: 3
2022-07-19 23:28:40,669:INFO:master_model_container: 3
2022-07-19 23:28:40,669:INFO:display_container: 1
2022-07-19 23:28:40,669:INFO:Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=4755, solver='auto', tol=0.001)
2022-07-19 23:28:40,669:INFO:create_model() succesfully completed......................................
2022-07-19 23:28:40,722:INFO:SubProcess create_model() end ==================================
2022-07-19 23:28:40,722:INFO:Creating metrics dataframe
2022-07-19 23:28:40,737:INFO:Initializing Elastic Net
2022-07-19 23:28:40,737:INFO:Total runtime is 0.056414266427357994 minutes
2022-07-19 23:28:40,742:INFO:SubProcess create_model() called ==================================
2022-07-19 23:28:40,742:INFO:Initializing create_model()
2022-07-19 23:28:40,742:INFO:create_model(estimator=en, fold=KFold(n_splits=10, random_state=4755, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdbda142430>, kwargs={})
2022-07-19 23:28:40,742:INFO:Checking exceptions
2022-07-19 23:28:40,742:INFO:Importing libraries
2022-07-19 23:28:40,742:INFO:Copying training dataset
2022-07-19 23:28:40,743:INFO:Defining folds
2022-07-19 23:28:40,743:INFO:Declaring metric variables
2022-07-19 23:28:40,747:INFO:Importing untrained model
2022-07-19 23:28:40,752:INFO:Elastic Net Imported succesfully
2022-07-19 23:28:40,761:INFO:Starting cross validation
2022-07-19 23:28:40,761:INFO:Cross validating with KFold(n_splits=10, random_state=4755, shuffle=False), n_jobs=-1
2022-07-19 23:28:40,795:INFO:Calculating mean and std
2022-07-19 23:28:40,796:INFO:Creating metrics dataframe
2022-07-19 23:28:40,812:INFO:Uploading results into container
2022-07-19 23:28:40,812:INFO:Uploading model into container now
2022-07-19 23:28:40,812:INFO:create_model_container: 4
2022-07-19 23:28:40,812:INFO:master_model_container: 4
2022-07-19 23:28:40,812:INFO:display_container: 1
2022-07-19 23:28:40,812:INFO:ElasticNet(alpha=1.0, copy_X=True, fit_intercept=True, l1_ratio=0.5,
           max_iter=1000, normalize=False, positive=False, precompute=False,
           random_state=4755, selection='cyclic', tol=0.0001, warm_start=False)
2022-07-19 23:28:40,812:INFO:create_model() succesfully completed......................................
2022-07-19 23:28:40,866:INFO:SubProcess create_model() end ==================================
2022-07-19 23:28:40,866:INFO:Creating metrics dataframe
2022-07-19 23:28:40,879:INFO:Initializing Least Angle Regression
2022-07-19 23:28:40,879:INFO:Total runtime is 0.05878043174743652 minutes
2022-07-19 23:28:40,884:INFO:SubProcess create_model() called ==================================
2022-07-19 23:28:40,884:INFO:Initializing create_model()
2022-07-19 23:28:40,884:INFO:create_model(estimator=lar, fold=KFold(n_splits=10, random_state=4755, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdbda142430>, kwargs={})
2022-07-19 23:28:40,884:INFO:Checking exceptions
2022-07-19 23:28:40,884:INFO:Importing libraries
2022-07-19 23:28:40,884:INFO:Copying training dataset
2022-07-19 23:28:40,885:INFO:Defining folds
2022-07-19 23:28:40,885:INFO:Declaring metric variables
2022-07-19 23:28:40,889:INFO:Importing untrained model
2022-07-19 23:28:40,894:INFO:Least Angle Regression Imported succesfully
2022-07-19 23:28:40,903:INFO:Starting cross validation
2022-07-19 23:28:40,903:INFO:Cross validating with KFold(n_splits=10, random_state=4755, shuffle=False), n_jobs=-1
2022-07-19 23:28:40,978:INFO:Calculating mean and std
2022-07-19 23:28:40,979:INFO:Creating metrics dataframe
2022-07-19 23:28:40,994:INFO:Uploading results into container
2022-07-19 23:28:40,995:INFO:Uploading model into container now
2022-07-19 23:28:40,995:INFO:create_model_container: 5
2022-07-19 23:28:40,995:INFO:master_model_container: 5
2022-07-19 23:28:40,995:INFO:display_container: 1
2022-07-19 23:28:40,995:INFO:Lars(copy_X=True, eps=2.220446049250313e-16, fit_intercept=True, fit_path=True,
     jitter=None, n_nonzero_coefs=500, normalize=True, precompute='auto',
     random_state=4755, verbose=False)
2022-07-19 23:28:40,995:INFO:create_model() succesfully completed......................................
2022-07-19 23:28:41,049:INFO:SubProcess create_model() end ==================================
2022-07-19 23:28:41,049:INFO:Creating metrics dataframe
2022-07-19 23:28:41,063:INFO:Initializing Lasso Least Angle Regression
2022-07-19 23:28:41,063:INFO:Total runtime is 0.06184303363164266 minutes
2022-07-19 23:28:41,067:INFO:SubProcess create_model() called ==================================
2022-07-19 23:28:41,068:INFO:Initializing create_model()
2022-07-19 23:28:41,068:INFO:create_model(estimator=llar, fold=KFold(n_splits=10, random_state=4755, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdbda142430>, kwargs={})
2022-07-19 23:28:41,068:INFO:Checking exceptions
2022-07-19 23:28:41,068:INFO:Importing libraries
2022-07-19 23:28:41,068:INFO:Copying training dataset
2022-07-19 23:28:41,069:INFO:Defining folds
2022-07-19 23:28:41,069:INFO:Declaring metric variables
2022-07-19 23:28:41,073:INFO:Importing untrained model
2022-07-19 23:28:41,077:INFO:Lasso Least Angle Regression Imported succesfully
2022-07-19 23:28:41,087:INFO:Starting cross validation
2022-07-19 23:28:41,088:INFO:Cross validating with KFold(n_splits=10, random_state=4755, shuffle=False), n_jobs=-1
2022-07-19 23:28:41,128:INFO:Calculating mean and std
2022-07-19 23:28:41,129:INFO:Creating metrics dataframe
2022-07-19 23:28:41,143:INFO:Uploading results into container
2022-07-19 23:28:41,144:INFO:Uploading model into container now
2022-07-19 23:28:41,144:INFO:create_model_container: 6
2022-07-19 23:28:41,144:INFO:master_model_container: 6
2022-07-19 23:28:41,144:INFO:display_container: 1
2022-07-19 23:28:41,144:INFO:LassoLars(alpha=1.0, copy_X=True, eps=2.220446049250313e-16, fit_intercept=True,
          fit_path=True, jitter=None, max_iter=500, normalize=True,
          positive=False, precompute='auto', random_state=4755, verbose=False)
2022-07-19 23:28:41,144:INFO:create_model() succesfully completed......................................
2022-07-19 23:28:41,198:INFO:SubProcess create_model() end ==================================
2022-07-19 23:28:41,198:INFO:Creating metrics dataframe
2022-07-19 23:28:41,213:INFO:Initializing Orthogonal Matching Pursuit
2022-07-19 23:28:41,213:INFO:Total runtime is 0.06434354782104493 minutes
2022-07-19 23:28:41,217:INFO:SubProcess create_model() called ==================================
2022-07-19 23:28:41,218:INFO:Initializing create_model()
2022-07-19 23:28:41,218:INFO:create_model(estimator=omp, fold=KFold(n_splits=10, random_state=4755, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdbda142430>, kwargs={})
2022-07-19 23:28:41,218:INFO:Checking exceptions
2022-07-19 23:28:41,218:INFO:Importing libraries
2022-07-19 23:28:41,218:INFO:Copying training dataset
2022-07-19 23:28:41,219:INFO:Defining folds
2022-07-19 23:28:41,219:INFO:Declaring metric variables
2022-07-19 23:28:41,223:INFO:Importing untrained model
2022-07-19 23:28:41,227:INFO:Orthogonal Matching Pursuit Imported succesfully
2022-07-19 23:28:41,236:INFO:Starting cross validation
2022-07-19 23:28:41,236:INFO:Cross validating with KFold(n_splits=10, random_state=4755, shuffle=False), n_jobs=-1
2022-07-19 23:28:41,271:INFO:Calculating mean and std
2022-07-19 23:28:41,272:INFO:Creating metrics dataframe
2022-07-19 23:28:41,287:INFO:Uploading results into container
2022-07-19 23:28:41,288:INFO:Uploading model into container now
2022-07-19 23:28:41,288:INFO:create_model_container: 7
2022-07-19 23:28:41,288:INFO:master_model_container: 7
2022-07-19 23:28:41,288:INFO:display_container: 1
2022-07-19 23:28:41,288:INFO:OrthogonalMatchingPursuit(fit_intercept=True, n_nonzero_coefs=None,
                          normalize=True, precompute='auto', tol=None)
2022-07-19 23:28:41,288:INFO:create_model() succesfully completed......................................
2022-07-19 23:28:41,340:INFO:SubProcess create_model() end ==================================
2022-07-19 23:28:41,340:INFO:Creating metrics dataframe
2022-07-19 23:28:41,354:INFO:Initializing Bayesian Ridge
2022-07-19 23:28:41,354:INFO:Total runtime is 0.066696834564209 minutes
2022-07-19 23:28:41,359:INFO:SubProcess create_model() called ==================================
2022-07-19 23:28:41,359:INFO:Initializing create_model()
2022-07-19 23:28:41,359:INFO:create_model(estimator=br, fold=KFold(n_splits=10, random_state=4755, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdbda142430>, kwargs={})
2022-07-19 23:28:41,359:INFO:Checking exceptions
2022-07-19 23:28:41,359:INFO:Importing libraries
2022-07-19 23:28:41,359:INFO:Copying training dataset
2022-07-19 23:28:41,359:INFO:Defining folds
2022-07-19 23:28:41,359:INFO:Declaring metric variables
2022-07-19 23:28:41,364:INFO:Importing untrained model
2022-07-19 23:28:41,368:INFO:Bayesian Ridge Imported succesfully
2022-07-19 23:28:41,377:INFO:Starting cross validation
2022-07-19 23:28:41,378:INFO:Cross validating with KFold(n_splits=10, random_state=4755, shuffle=False), n_jobs=-1
2022-07-19 23:28:41,490:INFO:Calculating mean and std
2022-07-19 23:28:41,491:INFO:Creating metrics dataframe
2022-07-19 23:28:41,506:INFO:Uploading results into container
2022-07-19 23:28:41,506:INFO:Uploading model into container now
2022-07-19 23:28:41,506:INFO:create_model_container: 8
2022-07-19 23:28:41,506:INFO:master_model_container: 8
2022-07-19 23:28:41,506:INFO:display_container: 1
2022-07-19 23:28:41,506:INFO:BayesianRidge(alpha_1=1e-06, alpha_2=1e-06, alpha_init=None,
              compute_score=False, copy_X=True, fit_intercept=True,
              lambda_1=1e-06, lambda_2=1e-06, lambda_init=None, n_iter=300,
              normalize=False, tol=0.001, verbose=False)
2022-07-19 23:28:41,506:INFO:create_model() succesfully completed......................................
2022-07-19 23:28:41,560:INFO:SubProcess create_model() end ==================================
2022-07-19 23:28:41,560:INFO:Creating metrics dataframe
2022-07-19 23:28:41,574:INFO:Initializing Passive Aggressive Regressor
2022-07-19 23:28:41,574:INFO:Total runtime is 0.07036168177922568 minutes
2022-07-19 23:28:41,579:INFO:SubProcess create_model() called ==================================
2022-07-19 23:28:41,579:INFO:Initializing create_model()
2022-07-19 23:28:41,579:INFO:create_model(estimator=par, fold=KFold(n_splits=10, random_state=4755, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdbda142430>, kwargs={})
2022-07-19 23:28:41,579:INFO:Checking exceptions
2022-07-19 23:28:41,579:INFO:Importing libraries
2022-07-19 23:28:41,579:INFO:Copying training dataset
2022-07-19 23:28:41,580:INFO:Defining folds
2022-07-19 23:28:41,580:INFO:Declaring metric variables
2022-07-19 23:28:41,584:INFO:Importing untrained model
2022-07-19 23:28:41,589:INFO:Passive Aggressive Regressor Imported succesfully
2022-07-19 23:28:41,599:INFO:Starting cross validation
2022-07-19 23:28:41,599:INFO:Cross validating with KFold(n_splits=10, random_state=4755, shuffle=False), n_jobs=-1
2022-07-19 23:28:41,648:INFO:Calculating mean and std
2022-07-19 23:28:41,649:INFO:Creating metrics dataframe
2022-07-19 23:28:41,665:INFO:Uploading results into container
2022-07-19 23:28:41,665:INFO:Uploading model into container now
2022-07-19 23:28:41,665:INFO:create_model_container: 9
2022-07-19 23:28:41,665:INFO:master_model_container: 9
2022-07-19 23:28:41,665:INFO:display_container: 1
2022-07-19 23:28:41,665:INFO:PassiveAggressiveRegressor(C=1.0, average=False, early_stopping=False,
                           epsilon=0.1, fit_intercept=True,
                           loss='epsilon_insensitive', max_iter=1000,
                           n_iter_no_change=5, random_state=4755, shuffle=True,
                           tol=0.001, validation_fraction=0.1, verbose=0,
                           warm_start=False)
2022-07-19 23:28:41,665:INFO:create_model() succesfully completed......................................
2022-07-19 23:28:41,719:INFO:SubProcess create_model() end ==================================
2022-07-19 23:28:41,720:INFO:Creating metrics dataframe
2022-07-19 23:28:41,734:INFO:Initializing Huber Regressor
2022-07-19 23:28:41,734:INFO:Total runtime is 0.07303185065587363 minutes
2022-07-19 23:28:41,738:INFO:SubProcess create_model() called ==================================
2022-07-19 23:28:41,739:INFO:Initializing create_model()
2022-07-19 23:28:41,739:INFO:create_model(estimator=huber, fold=KFold(n_splits=10, random_state=4755, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdbda142430>, kwargs={})
2022-07-19 23:28:41,739:INFO:Checking exceptions
2022-07-19 23:28:41,739:INFO:Importing libraries
2022-07-19 23:28:41,739:INFO:Copying training dataset
2022-07-19 23:28:41,740:INFO:Defining folds
2022-07-19 23:28:41,740:INFO:Declaring metric variables
2022-07-19 23:28:41,743:INFO:Importing untrained model
2022-07-19 23:28:41,748:INFO:Huber Regressor Imported succesfully
2022-07-19 23:28:41,757:INFO:Starting cross validation
2022-07-19 23:28:41,757:INFO:Cross validating with KFold(n_splits=10, random_state=4755, shuffle=False), n_jobs=-1
2022-07-19 23:28:41,877:INFO:Calculating mean and std
2022-07-19 23:28:41,877:INFO:Creating metrics dataframe
2022-07-19 23:28:41,891:INFO:Uploading results into container
2022-07-19 23:28:41,891:INFO:Uploading model into container now
2022-07-19 23:28:41,891:INFO:create_model_container: 10
2022-07-19 23:28:41,891:INFO:master_model_container: 10
2022-07-19 23:28:41,891:INFO:display_container: 1
2022-07-19 23:28:41,892:INFO:HuberRegressor(alpha=0.0001, epsilon=1.35, fit_intercept=True, max_iter=100,
               tol=1e-05, warm_start=False)
2022-07-19 23:28:41,892:INFO:create_model() succesfully completed......................................
2022-07-19 23:28:41,943:WARNING:create_model() for HuberRegressor(alpha=0.0001, epsilon=1.35, fit_intercept=True, max_iter=100,
               tol=1e-05, warm_start=False) raised an exception or returned all 0.0, trying without fit_kwargs:
2022-07-19 23:28:41,943:WARNING:Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2149, in compare_models
    assert np.sum(model_results.iloc[0]) != 0.0
AssertionError

2022-07-19 23:28:41,944:INFO:Initializing create_model()
2022-07-19 23:28:41,944:INFO:create_model(estimator=HuberRegressor(alpha=0.0001, epsilon=1.35, fit_intercept=True, max_iter=100,
               tol=1e-05, warm_start=False), fold=KFold(n_splits=10, random_state=4755, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdbda142430>, kwargs={})
2022-07-19 23:28:41,944:INFO:Checking exceptions
2022-07-19 23:28:41,944:INFO:Importing libraries
2022-07-19 23:28:41,944:INFO:Copying training dataset
2022-07-19 23:28:41,944:INFO:Defining folds
2022-07-19 23:28:41,944:INFO:Declaring metric variables
2022-07-19 23:28:41,949:INFO:Importing untrained model
2022-07-19 23:28:41,949:INFO:Declaring custom model
2022-07-19 23:28:41,953:INFO:Huber Regressor Imported succesfully
2022-07-19 23:28:41,961:INFO:Starting cross validation
2022-07-19 23:28:41,962:INFO:Cross validating with KFold(n_splits=10, random_state=4755, shuffle=False), n_jobs=-1
2022-07-19 23:28:42,128:INFO:Calculating mean and std
2022-07-19 23:28:42,129:INFO:Creating metrics dataframe
2022-07-19 23:28:42,145:INFO:Uploading results into container
2022-07-19 23:28:42,145:INFO:Uploading model into container now
2022-07-19 23:28:42,145:INFO:create_model_container: 11
2022-07-19 23:28:42,145:INFO:master_model_container: 11
2022-07-19 23:28:42,145:INFO:display_container: 1
2022-07-19 23:28:42,145:INFO:HuberRegressor(alpha=0.0001, epsilon=1.35, fit_intercept=True, max_iter=100,
               tol=1e-05, warm_start=False)
2022-07-19 23:28:42,145:INFO:create_model() succesfully completed......................................
2022-07-19 23:28:42,199:INFO:SubProcess create_model() end ==================================
2022-07-19 23:28:42,200:INFO:Creating metrics dataframe
2022-07-19 23:28:42,214:INFO:Initializing K Neighbors Regressor
2022-07-19 23:28:42,214:INFO:Total runtime is 0.08102484941482545 minutes
2022-07-19 23:28:42,218:INFO:SubProcess create_model() called ==================================
2022-07-19 23:28:42,219:INFO:Initializing create_model()
2022-07-19 23:28:42,219:INFO:create_model(estimator=knn, fold=KFold(n_splits=10, random_state=4755, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdbda142430>, kwargs={})
2022-07-19 23:28:42,219:INFO:Checking exceptions
2022-07-19 23:28:42,219:INFO:Importing libraries
2022-07-19 23:28:42,219:INFO:Copying training dataset
2022-07-19 23:28:42,219:INFO:Defining folds
2022-07-19 23:28:42,219:INFO:Declaring metric variables
2022-07-19 23:28:42,223:INFO:Importing untrained model
2022-07-19 23:28:42,228:INFO:K Neighbors Regressor Imported succesfully
2022-07-19 23:28:42,235:INFO:Starting cross validation
2022-07-19 23:28:42,236:INFO:Cross validating with KFold(n_splits=10, random_state=4755, shuffle=False), n_jobs=-1
2022-07-19 23:28:42,293:INFO:Calculating mean and std
2022-07-19 23:28:42,294:INFO:Creating metrics dataframe
2022-07-19 23:28:42,307:INFO:Uploading results into container
2022-07-19 23:28:42,307:INFO:Uploading model into container now
2022-07-19 23:28:42,307:INFO:create_model_container: 12
2022-07-19 23:28:42,307:INFO:master_model_container: 12
2022-07-19 23:28:42,307:INFO:display_container: 1
2022-07-19 23:28:42,307:INFO:KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                    weights='uniform')
2022-07-19 23:28:42,307:INFO:create_model() succesfully completed......................................
2022-07-19 23:28:42,359:INFO:SubProcess create_model() end ==================================
2022-07-19 23:28:42,359:INFO:Creating metrics dataframe
2022-07-19 23:28:42,373:INFO:Initializing Decision Tree Regressor
2022-07-19 23:28:42,373:INFO:Total runtime is 0.08368620077768962 minutes
2022-07-19 23:28:42,378:INFO:SubProcess create_model() called ==================================
2022-07-19 23:28:42,378:INFO:Initializing create_model()
2022-07-19 23:28:42,378:INFO:create_model(estimator=dt, fold=KFold(n_splits=10, random_state=4755, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdbda142430>, kwargs={})
2022-07-19 23:28:42,378:INFO:Checking exceptions
2022-07-19 23:28:42,378:INFO:Importing libraries
2022-07-19 23:28:42,378:INFO:Copying training dataset
2022-07-19 23:28:42,379:INFO:Defining folds
2022-07-19 23:28:42,379:INFO:Declaring metric variables
2022-07-19 23:28:42,382:INFO:Importing untrained model
2022-07-19 23:28:42,387:INFO:Decision Tree Regressor Imported succesfully
2022-07-19 23:28:42,396:INFO:Starting cross validation
2022-07-19 23:28:42,396:INFO:Cross validating with KFold(n_splits=10, random_state=4755, shuffle=False), n_jobs=-1
2022-07-19 23:28:42,453:INFO:Calculating mean and std
2022-07-19 23:28:42,454:INFO:Creating metrics dataframe
2022-07-19 23:28:42,468:INFO:Uploading results into container
2022-07-19 23:28:42,468:INFO:Uploading model into container now
2022-07-19 23:28:42,468:INFO:create_model_container: 13
2022-07-19 23:28:42,469:INFO:master_model_container: 13
2022-07-19 23:28:42,469:INFO:display_container: 1
2022-07-19 23:28:42,469:INFO:DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=4755, splitter='best')
2022-07-19 23:28:42,469:INFO:create_model() succesfully completed......................................
2022-07-19 23:28:42,521:INFO:SubProcess create_model() end ==================================
2022-07-19 23:28:42,521:INFO:Creating metrics dataframe
2022-07-19 23:28:42,535:INFO:Initializing Random Forest Regressor
2022-07-19 23:28:42,535:INFO:Total runtime is 0.08637523253758748 minutes
2022-07-19 23:28:42,539:INFO:SubProcess create_model() called ==================================
2022-07-19 23:28:42,539:INFO:Initializing create_model()
2022-07-19 23:28:42,539:INFO:create_model(estimator=rf, fold=KFold(n_splits=10, random_state=4755, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdbda142430>, kwargs={})
2022-07-19 23:28:42,539:INFO:Checking exceptions
2022-07-19 23:28:42,540:INFO:Importing libraries
2022-07-19 23:28:42,540:INFO:Copying training dataset
2022-07-19 23:28:42,540:INFO:Defining folds
2022-07-19 23:28:42,540:INFO:Declaring metric variables
2022-07-19 23:28:42,544:INFO:Importing untrained model
2022-07-19 23:28:42,548:INFO:Random Forest Regressor Imported succesfully
2022-07-19 23:28:42,556:INFO:Starting cross validation
2022-07-19 23:28:42,556:INFO:Cross validating with KFold(n_splits=10, random_state=4755, shuffle=False), n_jobs=-1
2022-07-19 23:28:43,823:INFO:Calculating mean and std
2022-07-19 23:28:43,824:INFO:Creating metrics dataframe
2022-07-19 23:28:43,841:INFO:Uploading results into container
2022-07-19 23:28:43,841:INFO:Uploading model into container now
2022-07-19 23:28:43,841:INFO:create_model_container: 14
2022-07-19 23:28:43,841:INFO:master_model_container: 14
2022-07-19 23:28:43,841:INFO:display_container: 1
2022-07-19 23:28:43,842:INFO:RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=-1, oob_score=False,
                      random_state=4755, verbose=0, warm_start=False)
2022-07-19 23:28:43,842:INFO:create_model() succesfully completed......................................
2022-07-19 23:28:43,896:INFO:SubProcess create_model() end ==================================
2022-07-19 23:28:43,896:INFO:Creating metrics dataframe
2022-07-19 23:28:43,911:INFO:Initializing Extra Trees Regressor
2022-07-19 23:28:43,911:INFO:Total runtime is 0.10931953191757202 minutes
2022-07-19 23:28:43,916:INFO:SubProcess create_model() called ==================================
2022-07-19 23:28:43,917:INFO:Initializing create_model()
2022-07-19 23:28:43,917:INFO:create_model(estimator=et, fold=KFold(n_splits=10, random_state=4755, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdbda142430>, kwargs={})
2022-07-19 23:28:43,917:INFO:Checking exceptions
2022-07-19 23:28:43,917:INFO:Importing libraries
2022-07-19 23:28:43,917:INFO:Copying training dataset
2022-07-19 23:28:43,918:INFO:Defining folds
2022-07-19 23:28:43,918:INFO:Declaring metric variables
2022-07-19 23:28:43,922:INFO:Importing untrained model
2022-07-19 23:28:43,926:INFO:Extra Trees Regressor Imported succesfully
2022-07-19 23:28:43,935:INFO:Starting cross validation
2022-07-19 23:28:43,935:INFO:Cross validating with KFold(n_splits=10, random_state=4755, shuffle=False), n_jobs=-1
2022-07-19 23:28:45,094:INFO:Calculating mean and std
2022-07-19 23:28:45,095:INFO:Creating metrics dataframe
2022-07-19 23:28:45,110:INFO:Uploading results into container
2022-07-19 23:28:45,110:INFO:Uploading model into container now
2022-07-19 23:28:45,110:INFO:create_model_container: 15
2022-07-19 23:28:45,110:INFO:master_model_container: 15
2022-07-19 23:28:45,110:INFO:display_container: 1
2022-07-19 23:28:45,111:INFO:ExtraTreesRegressor(bootstrap=False, ccp_alpha=0.0, criterion='mse',
                    max_depth=None, max_features='auto', max_leaf_nodes=None,
                    max_samples=None, min_impurity_decrease=0.0,
                    min_impurity_split=None, min_samples_leaf=1,
                    min_samples_split=2, min_weight_fraction_leaf=0.0,
                    n_estimators=100, n_jobs=-1, oob_score=False,
                    random_state=4755, verbose=0, warm_start=False)
2022-07-19 23:28:45,111:INFO:create_model() succesfully completed......................................
2022-07-19 23:28:45,167:INFO:SubProcess create_model() end ==================================
2022-07-19 23:28:45,167:INFO:Creating metrics dataframe
2022-07-19 23:28:45,182:INFO:Initializing AdaBoost Regressor
2022-07-19 23:28:45,182:INFO:Total runtime is 0.13049548467000324 minutes
2022-07-19 23:28:45,186:INFO:SubProcess create_model() called ==================================
2022-07-19 23:28:45,187:INFO:Initializing create_model()
2022-07-19 23:28:45,187:INFO:create_model(estimator=ada, fold=KFold(n_splits=10, random_state=4755, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdbda142430>, kwargs={})
2022-07-19 23:28:45,187:INFO:Checking exceptions
2022-07-19 23:28:45,187:INFO:Importing libraries
2022-07-19 23:28:45,187:INFO:Copying training dataset
2022-07-19 23:28:45,188:INFO:Defining folds
2022-07-19 23:28:45,188:INFO:Declaring metric variables
2022-07-19 23:28:45,192:INFO:Importing untrained model
2022-07-19 23:28:45,197:INFO:AdaBoost Regressor Imported succesfully
2022-07-19 23:28:45,211:INFO:Starting cross validation
2022-07-19 23:28:45,212:INFO:Cross validating with KFold(n_splits=10, random_state=4755, shuffle=False), n_jobs=-1
2022-07-19 23:28:45,540:INFO:Calculating mean and std
2022-07-19 23:28:45,541:INFO:Creating metrics dataframe
2022-07-19 23:28:45,559:INFO:Uploading results into container
2022-07-19 23:28:45,559:INFO:Uploading model into container now
2022-07-19 23:28:45,559:INFO:create_model_container: 16
2022-07-19 23:28:45,559:INFO:master_model_container: 16
2022-07-19 23:28:45,559:INFO:display_container: 1
2022-07-19 23:28:45,559:INFO:AdaBoostRegressor(base_estimator=None, learning_rate=1.0, loss='linear',
                  n_estimators=50, random_state=4755)
2022-07-19 23:28:45,559:INFO:create_model() succesfully completed......................................
2022-07-19 23:28:45,614:INFO:SubProcess create_model() end ==================================
2022-07-19 23:28:45,614:INFO:Creating metrics dataframe
2022-07-19 23:28:45,629:INFO:Initializing Gradient Boosting Regressor
2022-07-19 23:28:45,629:INFO:Total runtime is 0.1379526654879252 minutes
2022-07-19 23:28:45,634:INFO:SubProcess create_model() called ==================================
2022-07-19 23:28:45,634:INFO:Initializing create_model()
2022-07-19 23:28:45,634:INFO:create_model(estimator=gbr, fold=KFold(n_splits=10, random_state=4755, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdbda142430>, kwargs={})
2022-07-19 23:28:45,635:INFO:Checking exceptions
2022-07-19 23:28:45,635:INFO:Importing libraries
2022-07-19 23:28:45,635:INFO:Copying training dataset
2022-07-19 23:28:45,635:INFO:Defining folds
2022-07-19 23:28:45,635:INFO:Declaring metric variables
2022-07-19 23:28:45,639:INFO:Importing untrained model
2022-07-19 23:28:45,644:INFO:Gradient Boosting Regressor Imported succesfully
2022-07-19 23:28:45,653:INFO:Starting cross validation
2022-07-19 23:28:45,653:INFO:Cross validating with KFold(n_splits=10, random_state=4755, shuffle=False), n_jobs=-1
2022-07-19 23:28:46,294:INFO:Calculating mean and std
2022-07-19 23:28:46,295:INFO:Creating metrics dataframe
2022-07-19 23:28:46,311:INFO:Uploading results into container
2022-07-19 23:28:46,311:INFO:Uploading model into container now
2022-07-19 23:28:46,311:INFO:create_model_container: 17
2022-07-19 23:28:46,311:INFO:master_model_container: 17
2022-07-19 23:28:46,311:INFO:display_container: 1
2022-07-19 23:28:46,312:INFO:GradientBoostingRegressor(alpha=0.9, ccp_alpha=0.0, criterion='friedman_mse',
                          init=None, learning_rate=0.1, loss='ls', max_depth=3,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=100,
                          n_iter_no_change=None, presort='deprecated',
                          random_state=4755, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)
2022-07-19 23:28:46,312:INFO:create_model() succesfully completed......................................
2022-07-19 23:28:46,368:INFO:SubProcess create_model() end ==================================
2022-07-19 23:28:46,368:INFO:Creating metrics dataframe
2022-07-19 23:28:46,385:INFO:Initializing Extreme Gradient Boosting
2022-07-19 23:28:46,385:INFO:Total runtime is 0.15054241816202799 minutes
2022-07-19 23:28:46,390:INFO:SubProcess create_model() called ==================================
2022-07-19 23:28:46,390:INFO:Initializing create_model()
2022-07-19 23:28:46,390:INFO:create_model(estimator=xgboost, fold=KFold(n_splits=10, random_state=4755, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdbda142430>, kwargs={})
2022-07-19 23:28:46,390:INFO:Checking exceptions
2022-07-19 23:28:46,390:INFO:Importing libraries
2022-07-19 23:28:46,390:INFO:Copying training dataset
2022-07-19 23:28:46,391:INFO:Defining folds
2022-07-19 23:28:46,391:INFO:Declaring metric variables
2022-07-19 23:28:46,395:INFO:Importing untrained model
2022-07-19 23:28:46,400:INFO:Extreme Gradient Boosting Imported succesfully
2022-07-19 23:28:46,409:INFO:Starting cross validation
2022-07-19 23:28:46,410:INFO:Cross validating with KFold(n_splits=10, random_state=4755, shuffle=False), n_jobs=-1
2022-07-19 23:28:46,569:WARNING:create_model() for xgboost raised an exception or returned all 0.0, trying without fit_kwargs:
2022-07-19 23:28:46,572:WARNING:Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 242, in cross_validate
    scores = parallel(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/parallel.py", line 1056, in __call__
    self.retrieve()
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGSEGV(-11), SIGSEGV(-11), SIGSEGV(-11), SIGSEGV(-11)}

2022-07-19 23:28:46,572:INFO:Initializing create_model()
2022-07-19 23:28:46,572:INFO:create_model(estimator=xgboost, fold=KFold(n_splits=10, random_state=4755, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdbda142430>, kwargs={})
2022-07-19 23:28:46,572:INFO:Checking exceptions
2022-07-19 23:28:46,572:INFO:Importing libraries
2022-07-19 23:28:46,572:INFO:Copying training dataset
2022-07-19 23:28:46,573:INFO:Defining folds
2022-07-19 23:28:46,573:INFO:Declaring metric variables
2022-07-19 23:28:46,577:INFO:Importing untrained model
2022-07-19 23:28:46,584:INFO:Extreme Gradient Boosting Imported succesfully
2022-07-19 23:28:46,594:INFO:Starting cross validation
2022-07-19 23:28:46,595:INFO:Cross validating with KFold(n_splits=10, random_state=4755, shuffle=False), n_jobs=-1
2022-07-19 23:28:49,350:ERROR:create_model() for xgboost raised an exception:
2022-07-19 23:28:49,351:ERROR:Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 242, in cross_validate
    scores = parallel(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/parallel.py", line 1056, in __call__
    self.retrieve()
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGSEGV(-11), SIGSEGV(-11), SIGSEGV(-11), SIGSEGV(-11)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2156, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 242, in cross_validate
    scores = parallel(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/parallel.py", line 1056, in __call__
    self.retrieve()
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGSEGV(-11)}

2022-07-19 23:28:49,352:INFO:Initializing Light Gradient Boosting Machine
2022-07-19 23:28:49,352:INFO:Total runtime is 0.1999880830446879 minutes
2022-07-19 23:28:49,359:INFO:SubProcess create_model() called ==================================
2022-07-19 23:28:49,360:INFO:Initializing create_model()
2022-07-19 23:28:49,360:INFO:create_model(estimator=lightgbm, fold=KFold(n_splits=10, random_state=4755, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdbda142430>, kwargs={})
2022-07-19 23:28:49,360:INFO:Checking exceptions
2022-07-19 23:28:49,360:INFO:Importing libraries
2022-07-19 23:28:49,360:INFO:Copying training dataset
2022-07-19 23:28:49,361:INFO:Defining folds
2022-07-19 23:28:49,361:INFO:Declaring metric variables
2022-07-19 23:28:49,365:INFO:Importing untrained model
2022-07-19 23:28:49,370:INFO:Light Gradient Boosting Machine Imported succesfully
2022-07-19 23:28:49,378:INFO:Starting cross validation
2022-07-19 23:28:49,379:INFO:Cross validating with KFold(n_splits=10, random_state=4755, shuffle=False), n_jobs=-1
2022-07-19 23:28:51,828:INFO:Calculating mean and std
2022-07-19 23:28:51,829:INFO:Creating metrics dataframe
2022-07-19 23:28:51,854:INFO:Uploading results into container
2022-07-19 23:28:51,855:INFO:Uploading model into container now
2022-07-19 23:28:51,855:INFO:create_model_container: 18
2022-07-19 23:28:51,855:INFO:master_model_container: 18
2022-07-19 23:28:51,855:INFO:display_container: 1
2022-07-19 23:28:51,855:INFO:LGBMRegressor(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
              importance_type='split', learning_rate=0.1, max_depth=-1,
              min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
              n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
              random_state=4755, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
              subsample=1.0, subsample_for_bin=200000, subsample_freq=0)
2022-07-19 23:28:51,855:INFO:create_model() succesfully completed......................................
2022-07-19 23:28:51,929:INFO:SubProcess create_model() end ==================================
2022-07-19 23:28:51,929:INFO:Creating metrics dataframe
2022-07-19 23:28:51,944:INFO:Initializing CatBoost Regressor
2022-07-19 23:28:51,945:INFO:Total runtime is 0.24320438305536907 minutes
2022-07-19 23:28:51,949:INFO:SubProcess create_model() called ==================================
2022-07-19 23:28:51,949:INFO:Initializing create_model()
2022-07-19 23:28:51,949:INFO:create_model(estimator=catboost, fold=KFold(n_splits=10, random_state=4755, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdbda142430>, kwargs={})
2022-07-19 23:28:51,949:INFO:Checking exceptions
2022-07-19 23:28:51,949:INFO:Importing libraries
2022-07-19 23:28:51,949:INFO:Copying training dataset
2022-07-19 23:28:51,950:INFO:Defining folds
2022-07-19 23:28:51,950:INFO:Declaring metric variables
2022-07-19 23:28:51,954:INFO:Importing untrained model
2022-07-19 23:28:51,963:INFO:CatBoost Regressor Imported succesfully
2022-07-19 23:28:51,975:INFO:Starting cross validation
2022-07-19 23:28:51,977:INFO:Cross validating with KFold(n_splits=10, random_state=4755, shuffle=False), n_jobs=-1
2022-07-19 23:28:57,565:INFO:Calculating mean and std
2022-07-19 23:28:57,566:INFO:Creating metrics dataframe
2022-07-19 23:28:57,592:INFO:Uploading results into container
2022-07-19 23:28:57,592:INFO:Uploading model into container now
2022-07-19 23:28:57,592:INFO:create_model_container: 19
2022-07-19 23:28:57,592:INFO:master_model_container: 19
2022-07-19 23:28:57,592:INFO:display_container: 1
2022-07-19 23:28:57,593:INFO:<catboost.core.CatBoostRegressor object at 0x7fdbbacf3280>
2022-07-19 23:28:57,593:INFO:create_model() succesfully completed......................................
2022-07-19 23:28:57,674:INFO:SubProcess create_model() end ==================================
2022-07-19 23:28:57,674:INFO:Creating metrics dataframe
2022-07-19 23:28:57,700:INFO:Initializing create_model()
2022-07-19 23:28:57,700:INFO:create_model(estimator=<catboost.core.CatBoostRegressor object at 0x7fdbbacf3280>, fold=KFold(n_splits=10, random_state=4755, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, verbose=False, system=False, metrics=None, display=None, kwargs={})
2022-07-19 23:28:57,700:INFO:Checking exceptions
2022-07-19 23:28:57,700:INFO:Importing libraries
2022-07-19 23:28:57,701:INFO:Copying training dataset
2022-07-19 23:28:57,701:INFO:Defining folds
2022-07-19 23:28:57,701:INFO:Declaring metric variables
2022-07-19 23:28:57,701:INFO:Importing untrained model
2022-07-19 23:28:57,701:INFO:Declaring custom model
2022-07-19 23:28:57,701:INFO:CatBoost Regressor Imported succesfully
2022-07-19 23:28:57,702:INFO:Cross validation set to False
2022-07-19 23:28:57,702:INFO:Fitting Model
2022-07-19 23:28:59,232:INFO:<catboost.core.CatBoostRegressor object at 0x7fdbbacf3490>
2022-07-19 23:28:59,232:INFO:create_models() succesfully completed......................................
2022-07-19 23:28:59,301:INFO:create_model_container: 19
2022-07-19 23:28:59,302:INFO:master_model_container: 19
2022-07-19 23:28:59,302:INFO:display_container: 1
2022-07-19 23:28:59,302:INFO:<catboost.core.CatBoostRegressor object at 0x7fdbbacf3490>
2022-07-19 23:28:59,302:INFO:compare_models() succesfully completed......................................
2022-07-19 23:30:06,714:INFO:Initializing create_model()
2022-07-19 23:30:06,715:INFO:create_model(estimator=huber, fold=None, round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=True, verbose=True, system=True, metrics=None, display=None, kwargs={})
2022-07-19 23:30:06,715:INFO:Checking exceptions
2022-07-19 23:30:06,716:INFO:Preparing display monitor
2022-07-19 23:30:06,733:INFO:Importing libraries
2022-07-19 23:30:06,733:INFO:Copying training dataset
2022-07-19 23:30:06,735:INFO:Defining folds
2022-07-19 23:30:06,735:INFO:Declaring metric variables
2022-07-19 23:30:06,739:INFO:Importing untrained model
2022-07-19 23:30:06,743:INFO:Huber Regressor Imported succesfully
2022-07-19 23:30:06,752:INFO:Starting cross validation
2022-07-19 23:30:06,753:INFO:Cross validating with KFold(n_splits=10, random_state=4755, shuffle=False), n_jobs=-1
2022-07-19 23:30:06,970:INFO:Calculating mean and std
2022-07-19 23:30:06,971:INFO:Creating metrics dataframe
2022-07-19 23:30:07,014:INFO:Finalizing model
2022-07-19 23:30:59,685:INFO:Initializing create_model()
2022-07-19 23:30:59,692:INFO:create_model(estimator=rf, fold=None, round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=True, verbose=True, system=True, metrics=None, display=None, kwargs={})
2022-07-19 23:30:59,692:INFO:Checking exceptions
2022-07-19 23:30:59,693:INFO:Preparing display monitor
2022-07-19 23:30:59,726:INFO:Importing libraries
2022-07-19 23:30:59,726:INFO:Copying training dataset
2022-07-19 23:30:59,728:INFO:Defining folds
2022-07-19 23:30:59,728:INFO:Declaring metric variables
2022-07-19 23:30:59,732:INFO:Importing untrained model
2022-07-19 23:30:59,738:INFO:Random Forest Regressor Imported succesfully
2022-07-19 23:30:59,747:INFO:Starting cross validation
2022-07-19 23:30:59,748:INFO:Cross validating with KFold(n_splits=10, random_state=4755, shuffle=False), n_jobs=-1
2022-07-19 23:31:01,134:INFO:Calculating mean and std
2022-07-19 23:31:01,135:INFO:Creating metrics dataframe
2022-07-19 23:31:01,180:INFO:Finalizing model
2022-07-19 23:31:01,394:INFO:Uploading results into container
2022-07-19 23:31:01,394:INFO:Uploading model into container now
2022-07-19 23:31:01,400:INFO:create_model_container: 20
2022-07-19 23:31:01,400:INFO:master_model_container: 20
2022-07-19 23:31:01,400:INFO:display_container: 2
2022-07-19 23:31:01,400:INFO:RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=-1, oob_score=False,
                      random_state=4755, verbose=0, warm_start=False)
2022-07-19 23:31:01,400:INFO:create_model() succesfully completed......................................
2022-07-19 23:31:08,610:INFO:Initializing create_model()
2022-07-19 23:31:08,611:INFO:create_model(estimator=huber, fold=None, round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=True, verbose=True, system=True, metrics=None, display=None, kwargs={})
2022-07-19 23:31:08,611:INFO:Checking exceptions
2022-07-19 23:31:08,612:INFO:Preparing display monitor
2022-07-19 23:31:08,637:INFO:Importing libraries
2022-07-19 23:31:08,638:INFO:Copying training dataset
2022-07-19 23:31:08,643:INFO:Defining folds
2022-07-19 23:31:08,643:INFO:Declaring metric variables
2022-07-19 23:31:08,647:INFO:Importing untrained model
2022-07-19 23:31:08,653:INFO:Huber Regressor Imported succesfully
2022-07-19 23:31:08,668:INFO:Starting cross validation
2022-07-19 23:31:08,668:INFO:Cross validating with KFold(n_splits=10, random_state=4755, shuffle=False), n_jobs=-1
2022-07-19 23:31:08,806:INFO:Calculating mean and std
2022-07-19 23:31:08,807:INFO:Creating metrics dataframe
2022-07-19 23:31:08,827:INFO:Finalizing model
2022-07-19 23:34:10,599:INFO:PyCaret Supervised Module
2022-07-19 23:34:10,600:INFO:ML Usecase: regression
2022-07-19 23:34:10,600:INFO:version 2.2.2
2022-07-19 23:34:10,601:INFO:Initializing setup()
2022-07-19 23:34:10,609:INFO:setup(target=Attrition, ml_usecase=regression, available_plots={'parameter': 'Hyperparameters', 'residuals': 'Residuals', 'error': 'Prediction Error', 'cooks': 'Cooks Distance', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'vc': 'Validation Curve', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'tree': 'Decision Tree'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=kfold, fold=10, fold_shuffle=False, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=None, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2022-07-19 23:34:10,610:INFO:Checking environment
2022-07-19 23:34:10,610:INFO:python_version: 3.9.7
2022-07-19 23:34:10,610:INFO:python_build: ('default', 'Sep 16 2021 08:50:36')
2022-07-19 23:34:10,610:INFO:machine: x86_64
2022-07-19 23:34:10,610:INFO:platform: macOS-10.16-x86_64-i386-64bit
2022-07-19 23:34:10,611:INFO:Memory: svmem(total=17179869184, available=789655552, percent=95.4, used=1305047040, free=17666048, active=776175616, inactive=769314816, wired=528871424)
2022-07-19 23:34:10,611:INFO:Physical Core: 8
2022-07-19 23:34:10,611:INFO:Logical Core: 8
2022-07-19 23:34:10,611:INFO:Checking libraries
2022-07-19 23:34:10,611:INFO:pd==1.4.2
2022-07-19 23:34:10,611:INFO:numpy==1.21.5
2022-07-19 23:34:10,611:INFO:sklearn==0.23.2
2022-07-19 23:34:10,611:INFO:xgboost==1.5.2
2022-07-19 23:34:10,611:INFO:lightgbm==3.3.2
2022-07-19 23:34:10,612:INFO:catboost==1.0.4
2022-07-19 23:34:10,612:INFO:mlflow==1.24.0
2022-07-19 23:34:10,612:INFO:Checking Exceptions
2022-07-19 23:34:10,612:INFO:Declaring global variables
2022-07-19 23:34:10,612:INFO:USI: ae87
2022-07-19 23:34:10,612:INFO:pycaret_globals: {'_all_models_internal', 'fold_param', 'y_train', 'imputation_classifier', 'fix_imbalance_param', 'target_param', 'n_jobs_param', 'y_test', 'gpu_param', 'log_plots_param', 'prep_pipe', 'imputation_regressor', 'logging_param', 'exp_name_log', 'seed', '_ml_usecase', 'fold_generator', 'master_model_container', 'pycaret_globals', 'stratify_param', 'X_train', 'fold_shuffle_param', 'y', 'display_container', 'create_model_container', 'data_before_preprocess', '_all_metrics', 'X', 'X_test', 'experiment__', 'fix_imbalance_method_param', '_available_plots', 'iterative_imputation_iters_param', 'transform_target_param', 'transform_target_method_param', 'USI', 'html_param', 'fold_groups_param', '_all_models', '_internal_pipeline', '_gpu_n_jobs_param'}
2022-07-19 23:34:10,612:INFO:Preparing display monitor
2022-07-19 23:34:10,612:INFO:Preparing display monitor
2022-07-19 23:34:10,627:INFO:Importing libraries
2022-07-19 23:34:10,627:INFO:Copying data for preprocessing
2022-07-19 23:34:10,631:INFO:Declaring preprocessing parameters
2022-07-19 23:34:10,633:INFO:Creating preprocessing pipeline
2022-07-19 23:34:10,641:INFO:Preprocessing pipeline created successfully
2022-07-19 23:34:10,642:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2022-07-19 23:34:10,642:INFO:Creating global containers
2022-07-19 23:34:10,643:INFO:Internal pipeline: Pipeline(memory=None, steps=[('empty_step', 'passthrough')], verbose=False)
2022-07-19 23:34:14,040:INFO:Creating grid variables
2022-07-19 23:34:14,048:INFO:create_model_container: 0
2022-07-19 23:34:14,048:INFO:master_model_container: 0
2022-07-19 23:34:14,048:INFO:display_container: 0
2022-07-19 23:34:14,050:INFO:Pipeline(memory=None,
         steps=[('dtypes',
                 DataTypes_Auto_infer(categorical_features=[],
                                      display_types=True, features_todrop=[],
                                      id_columns=[],
                                      ml_usecase='classification',
                                      numerical_features=[], target='Attrition',
                                      time_features=[])),
                ('imputer',
                 Simple_Imputer(categorical_strategy='not_available',
                                fill_value_categorical=None,
                                fill_value_numerical=None,
                                numeric_st...
                ('scaling', 'passthrough'), ('P_transform', 'passthrough'),
                ('binn', 'passthrough'), ('rem_outliers', 'passthrough'),
                ('cluster_all', 'passthrough'),
                ('dummy', Dummify(target='Attrition')),
                ('fix_perfect', Remove_100(target='Attrition')),
                ('clean_names', Clean_Colum_Names()),
                ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                ('dfs', 'passthrough'), ('pca', 'passthrough')],
         verbose=False)
2022-07-19 23:34:14,051:INFO:setup() succesfully completed......................................
2022-07-19 23:34:25,404:INFO:Initializing compare_models()
2022-07-19 23:34:25,405:INFO:compare_models(include=None, fold=None, round=4, cross_validation=True, sort=R2, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, verbose=True, display=None, exclude=None)
2022-07-19 23:34:25,405:INFO:Checking exceptions
2022-07-19 23:34:25,406:INFO:Preparing display monitor
2022-07-19 23:34:25,406:INFO:Preparing display monitor
2022-07-19 23:34:25,438:INFO:Initializing Linear Regression
2022-07-19 23:34:25,438:INFO:Total runtime is 2.868970235188802e-06 minutes
2022-07-19 23:34:25,443:INFO:SubProcess create_model() called ==================================
2022-07-19 23:34:25,443:INFO:Initializing create_model()
2022-07-19 23:34:25,443:INFO:create_model(estimator=lr, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:34:25,443:INFO:Checking exceptions
2022-07-19 23:34:25,443:INFO:Importing libraries
2022-07-19 23:34:25,444:INFO:Copying training dataset
2022-07-19 23:34:25,445:INFO:Defining folds
2022-07-19 23:34:25,445:INFO:Declaring metric variables
2022-07-19 23:34:25,449:INFO:Importing untrained model
2022-07-19 23:34:25,453:INFO:Linear Regression Imported succesfully
2022-07-19 23:34:25,462:INFO:Starting cross validation
2022-07-19 23:34:25,462:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:34:25,580:INFO:Calculating mean and std
2022-07-19 23:34:25,581:INFO:Creating metrics dataframe
2022-07-19 23:34:25,597:INFO:Uploading results into container
2022-07-19 23:34:25,597:INFO:Uploading model into container now
2022-07-19 23:34:25,597:INFO:create_model_container: 1
2022-07-19 23:34:25,597:INFO:master_model_container: 1
2022-07-19 23:34:25,597:INFO:display_container: 1
2022-07-19 23:34:25,597:INFO:LinearRegression(copy_X=True, fit_intercept=True, n_jobs=-1, normalize=False)
2022-07-19 23:34:25,597:INFO:create_model() succesfully completed......................................
2022-07-19 23:34:25,688:INFO:SubProcess create_model() end ==================================
2022-07-19 23:34:25,688:INFO:Creating metrics dataframe
2022-07-19 23:34:25,700:INFO:Initializing Lasso Regression
2022-07-19 23:34:25,700:INFO:Total runtime is 0.00436936616897583 minutes
2022-07-19 23:34:25,705:INFO:SubProcess create_model() called ==================================
2022-07-19 23:34:25,705:INFO:Initializing create_model()
2022-07-19 23:34:25,706:INFO:create_model(estimator=lasso, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:34:25,706:INFO:Checking exceptions
2022-07-19 23:34:25,706:INFO:Importing libraries
2022-07-19 23:34:25,706:INFO:Copying training dataset
2022-07-19 23:34:25,707:INFO:Defining folds
2022-07-19 23:34:25,707:INFO:Declaring metric variables
2022-07-19 23:34:25,712:INFO:Importing untrained model
2022-07-19 23:34:25,716:INFO:Lasso Regression Imported succesfully
2022-07-19 23:34:25,725:INFO:Starting cross validation
2022-07-19 23:34:25,726:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:34:25,779:INFO:Calculating mean and std
2022-07-19 23:34:25,779:INFO:Creating metrics dataframe
2022-07-19 23:34:25,794:INFO:Uploading results into container
2022-07-19 23:34:25,795:INFO:Uploading model into container now
2022-07-19 23:34:25,795:INFO:create_model_container: 2
2022-07-19 23:34:25,795:INFO:master_model_container: 2
2022-07-19 23:34:25,795:INFO:display_container: 1
2022-07-19 23:34:25,795:INFO:Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=4476,
      selection='cyclic', tol=0.0001, warm_start=False)
2022-07-19 23:34:25,795:INFO:create_model() succesfully completed......................................
2022-07-19 23:34:25,879:INFO:SubProcess create_model() end ==================================
2022-07-19 23:34:25,879:INFO:Creating metrics dataframe
2022-07-19 23:34:25,892:INFO:Initializing Ridge Regression
2022-07-19 23:34:25,892:INFO:Total runtime is 0.007562700907389324 minutes
2022-07-19 23:34:25,896:INFO:SubProcess create_model() called ==================================
2022-07-19 23:34:25,896:INFO:Initializing create_model()
2022-07-19 23:34:25,896:INFO:create_model(estimator=ridge, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:34:25,897:INFO:Checking exceptions
2022-07-19 23:34:25,897:INFO:Importing libraries
2022-07-19 23:34:25,897:INFO:Copying training dataset
2022-07-19 23:34:25,897:INFO:Defining folds
2022-07-19 23:34:25,897:INFO:Declaring metric variables
2022-07-19 23:34:25,901:INFO:Importing untrained model
2022-07-19 23:34:25,905:INFO:Ridge Regression Imported succesfully
2022-07-19 23:34:25,913:INFO:Starting cross validation
2022-07-19 23:34:25,913:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:34:25,960:INFO:Calculating mean and std
2022-07-19 23:34:25,961:INFO:Creating metrics dataframe
2022-07-19 23:34:25,976:INFO:Uploading results into container
2022-07-19 23:34:25,977:INFO:Uploading model into container now
2022-07-19 23:34:25,977:INFO:create_model_container: 3
2022-07-19 23:34:25,977:INFO:master_model_container: 3
2022-07-19 23:34:25,977:INFO:display_container: 1
2022-07-19 23:34:25,977:INFO:Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=4476, solver='auto', tol=0.001)
2022-07-19 23:34:25,977:INFO:create_model() succesfully completed......................................
2022-07-19 23:34:26,059:INFO:SubProcess create_model() end ==================================
2022-07-19 23:34:26,059:INFO:Creating metrics dataframe
2022-07-19 23:34:26,072:INFO:Initializing Elastic Net
2022-07-19 23:34:26,072:INFO:Total runtime is 0.010562713940938315 minutes
2022-07-19 23:34:26,076:INFO:SubProcess create_model() called ==================================
2022-07-19 23:34:26,076:INFO:Initializing create_model()
2022-07-19 23:34:26,077:INFO:create_model(estimator=en, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:34:26,077:INFO:Checking exceptions
2022-07-19 23:34:26,077:INFO:Importing libraries
2022-07-19 23:34:26,077:INFO:Copying training dataset
2022-07-19 23:34:26,077:INFO:Defining folds
2022-07-19 23:34:26,077:INFO:Declaring metric variables
2022-07-19 23:34:26,081:INFO:Importing untrained model
2022-07-19 23:34:26,085:INFO:Elastic Net Imported succesfully
2022-07-19 23:34:26,093:INFO:Starting cross validation
2022-07-19 23:34:26,094:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:34:26,130:INFO:Calculating mean and std
2022-07-19 23:34:26,131:INFO:Creating metrics dataframe
2022-07-19 23:34:26,147:INFO:Uploading results into container
2022-07-19 23:34:26,147:INFO:Uploading model into container now
2022-07-19 23:34:26,147:INFO:create_model_container: 4
2022-07-19 23:34:26,147:INFO:master_model_container: 4
2022-07-19 23:34:26,147:INFO:display_container: 1
2022-07-19 23:34:26,148:INFO:ElasticNet(alpha=1.0, copy_X=True, fit_intercept=True, l1_ratio=0.5,
           max_iter=1000, normalize=False, positive=False, precompute=False,
           random_state=4476, selection='cyclic', tol=0.0001, warm_start=False)
2022-07-19 23:34:26,148:INFO:create_model() succesfully completed......................................
2022-07-19 23:34:26,235:INFO:SubProcess create_model() end ==================================
2022-07-19 23:34:26,235:INFO:Creating metrics dataframe
2022-07-19 23:34:26,248:INFO:Initializing Least Angle Regression
2022-07-19 23:34:26,248:INFO:Total runtime is 0.013500483830769858 minutes
2022-07-19 23:34:26,253:INFO:SubProcess create_model() called ==================================
2022-07-19 23:34:26,253:INFO:Initializing create_model()
2022-07-19 23:34:26,253:INFO:create_model(estimator=lar, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:34:26,253:INFO:Checking exceptions
2022-07-19 23:34:26,253:INFO:Importing libraries
2022-07-19 23:34:26,253:INFO:Copying training dataset
2022-07-19 23:34:26,254:INFO:Defining folds
2022-07-19 23:34:26,254:INFO:Declaring metric variables
2022-07-19 23:34:26,258:INFO:Importing untrained model
2022-07-19 23:34:26,263:INFO:Least Angle Regression Imported succesfully
2022-07-19 23:34:26,272:INFO:Starting cross validation
2022-07-19 23:34:26,273:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:34:26,605:WARNING:create_model() for lar raised an exception or returned all 0.0, trying without fit_kwargs:
2022-07-19 23:34:26,606:WARNING:joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 436, in _process_worker
    r = call_item()
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 288, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 560, in _fit_and_score
    If it is a single callable, the return value for ``train_scores`` and
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 607, in _score
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 87, in __call__
    ----------
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 212, in _score
    -------
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/metrics/_regression.py", line 178, in mean_absolute_error
    >>> y_true = [3, -0.5, 2, 7]
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/metrics/_regression.py", line 86, in _check_reg_targets
    uniform_average', 'variance_weighted'] or None
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 644, in check_array
    UInt16Dtype,
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 96, in _assert_all_finite
    return
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 242, in cross_validate
    See Also
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/parallel.py", line 1056, in __call__
    self.retrieve()
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

2022-07-19 23:34:26,606:INFO:Initializing create_model()
2022-07-19 23:34:26,606:INFO:create_model(estimator=lar, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:34:26,607:INFO:Checking exceptions
2022-07-19 23:34:26,607:INFO:Importing libraries
2022-07-19 23:34:26,607:INFO:Copying training dataset
2022-07-19 23:34:26,607:INFO:Defining folds
2022-07-19 23:34:26,607:INFO:Declaring metric variables
2022-07-19 23:34:26,611:INFO:Importing untrained model
2022-07-19 23:34:26,615:INFO:Least Angle Regression Imported succesfully
2022-07-19 23:34:26,624:INFO:Starting cross validation
2022-07-19 23:34:26,624:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:35:13,689:ERROR:create_model() for lar raised an exception:
2022-07-19 23:35:13,690:ERROR:joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 436, in _process_worker
    r = call_item()
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 288, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 560, in _fit_and_score
    If it is a single callable, the return value for ``train_scores`` and
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 607, in _score
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 87, in __call__
    ----------
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 212, in _score
    -------
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/metrics/_regression.py", line 178, in mean_absolute_error
    >>> y_true = [3, -0.5, 2, 7]
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/metrics/_regression.py", line 86, in _check_reg_targets
    uniform_average', 'variance_weighted'] or None
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 644, in check_array
    UInt16Dtype,
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 96, in _assert_all_finite
    return
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 242, in cross_validate
    See Also
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/parallel.py", line 1056, in __call__
    self.retrieve()
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2156, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-07-19 23:35:13,691:INFO:Initializing Lasso Least Angle Regression
2022-07-19 23:35:13,691:INFO:Total runtime is 0.8042122522989908 minutes
2022-07-19 23:35:13,709:INFO:SubProcess create_model() called ==================================
2022-07-19 23:35:13,710:INFO:Initializing create_model()
2022-07-19 23:35:13,711:INFO:create_model(estimator=llar, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:35:13,711:INFO:Checking exceptions
2022-07-19 23:35:13,711:INFO:Importing libraries
2022-07-19 23:35:13,711:INFO:Copying training dataset
2022-07-19 23:35:13,713:INFO:Defining folds
2022-07-19 23:35:13,713:INFO:Declaring metric variables
2022-07-19 23:35:13,719:INFO:Importing untrained model
2022-07-19 23:35:13,724:INFO:Lasso Least Angle Regression Imported succesfully
2022-07-19 23:35:13,737:INFO:Starting cross validation
2022-07-19 23:35:13,738:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:35:13,786:WARNING:create_model() for llar raised an exception or returned all 0.0, trying without fit_kwargs:
2022-07-19 23:35:13,786:WARNING:Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-07-19 23:35:13,786:INFO:Initializing create_model()
2022-07-19 23:35:13,786:INFO:create_model(estimator=llar, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:35:13,786:INFO:Checking exceptions
2022-07-19 23:35:13,786:INFO:Importing libraries
2022-07-19 23:35:13,786:INFO:Copying training dataset
2022-07-19 23:35:13,787:INFO:Defining folds
2022-07-19 23:35:13,787:INFO:Declaring metric variables
2022-07-19 23:35:13,793:INFO:Importing untrained model
2022-07-19 23:35:13,797:INFO:Lasso Least Angle Regression Imported succesfully
2022-07-19 23:35:13,806:INFO:Starting cross validation
2022-07-19 23:35:13,806:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:35:13,846:ERROR:create_model() for llar raised an exception:
2022-07-19 23:35:13,846:ERROR:Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2156, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-07-19 23:35:13,846:INFO:Initializing Orthogonal Matching Pursuit
2022-07-19 23:35:13,846:INFO:Total runtime is 0.8068016489346822 minutes
2022-07-19 23:35:13,851:INFO:SubProcess create_model() called ==================================
2022-07-19 23:35:13,851:INFO:Initializing create_model()
2022-07-19 23:35:13,851:INFO:create_model(estimator=omp, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:35:13,851:INFO:Checking exceptions
2022-07-19 23:35:13,851:INFO:Importing libraries
2022-07-19 23:35:13,851:INFO:Copying training dataset
2022-07-19 23:35:13,852:INFO:Defining folds
2022-07-19 23:35:13,852:INFO:Declaring metric variables
2022-07-19 23:35:13,856:INFO:Importing untrained model
2022-07-19 23:35:13,861:INFO:Orthogonal Matching Pursuit Imported succesfully
2022-07-19 23:35:13,869:INFO:Starting cross validation
2022-07-19 23:35:13,870:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:35:13,909:WARNING:create_model() for omp raised an exception or returned all 0.0, trying without fit_kwargs:
2022-07-19 23:35:13,909:WARNING:Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-07-19 23:35:13,909:INFO:Initializing create_model()
2022-07-19 23:35:13,909:INFO:create_model(estimator=omp, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:35:13,909:INFO:Checking exceptions
2022-07-19 23:35:13,909:INFO:Importing libraries
2022-07-19 23:35:13,909:INFO:Copying training dataset
2022-07-19 23:35:13,910:INFO:Defining folds
2022-07-19 23:35:13,910:INFO:Declaring metric variables
2022-07-19 23:35:13,914:INFO:Importing untrained model
2022-07-19 23:35:13,919:INFO:Orthogonal Matching Pursuit Imported succesfully
2022-07-19 23:35:13,927:INFO:Starting cross validation
2022-07-19 23:35:13,927:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:35:13,995:ERROR:create_model() for omp raised an exception:
2022-07-19 23:35:13,996:ERROR:Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2156, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-07-19 23:35:13,996:INFO:Initializing Bayesian Ridge
2022-07-19 23:35:13,996:INFO:Total runtime is 0.8093063513437907 minutes
2022-07-19 23:35:14,023:INFO:SubProcess create_model() called ==================================
2022-07-19 23:35:14,023:INFO:Initializing create_model()
2022-07-19 23:35:14,023:INFO:create_model(estimator=br, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:35:14,023:INFO:Checking exceptions
2022-07-19 23:35:14,023:INFO:Importing libraries
2022-07-19 23:35:14,023:INFO:Copying training dataset
2022-07-19 23:35:14,024:INFO:Defining folds
2022-07-19 23:35:14,024:INFO:Declaring metric variables
2022-07-19 23:35:14,028:INFO:Importing untrained model
2022-07-19 23:35:14,033:INFO:Bayesian Ridge Imported succesfully
2022-07-19 23:35:14,045:INFO:Starting cross validation
2022-07-19 23:35:14,046:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:35:14,123:WARNING:create_model() for br raised an exception or returned all 0.0, trying without fit_kwargs:
2022-07-19 23:35:14,124:WARNING:Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-07-19 23:35:14,124:INFO:Initializing create_model()
2022-07-19 23:35:14,124:INFO:create_model(estimator=br, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:35:14,124:INFO:Checking exceptions
2022-07-19 23:35:14,124:INFO:Importing libraries
2022-07-19 23:35:14,124:INFO:Copying training dataset
2022-07-19 23:35:14,125:INFO:Defining folds
2022-07-19 23:35:14,125:INFO:Declaring metric variables
2022-07-19 23:35:14,129:INFO:Importing untrained model
2022-07-19 23:35:14,135:INFO:Bayesian Ridge Imported succesfully
2022-07-19 23:35:14,143:INFO:Starting cross validation
2022-07-19 23:35:14,144:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:35:14,208:ERROR:create_model() for br raised an exception:
2022-07-19 23:35:14,209:ERROR:Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2156, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-07-19 23:35:14,209:INFO:Initializing Passive Aggressive Regressor
2022-07-19 23:35:14,209:INFO:Total runtime is 0.8128463824590048 minutes
2022-07-19 23:35:14,214:INFO:SubProcess create_model() called ==================================
2022-07-19 23:35:14,214:INFO:Initializing create_model()
2022-07-19 23:35:14,214:INFO:create_model(estimator=par, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:35:14,214:INFO:Checking exceptions
2022-07-19 23:35:14,214:INFO:Importing libraries
2022-07-19 23:35:14,214:INFO:Copying training dataset
2022-07-19 23:35:14,215:INFO:Defining folds
2022-07-19 23:35:14,215:INFO:Declaring metric variables
2022-07-19 23:35:14,219:INFO:Importing untrained model
2022-07-19 23:35:14,249:INFO:Passive Aggressive Regressor Imported succesfully
2022-07-19 23:35:14,259:INFO:Starting cross validation
2022-07-19 23:35:14,260:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:35:14,313:WARNING:create_model() for par raised an exception or returned all 0.0, trying without fit_kwargs:
2022-07-19 23:35:14,313:WARNING:Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-07-19 23:35:14,313:INFO:Initializing create_model()
2022-07-19 23:35:14,313:INFO:create_model(estimator=par, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:35:14,313:INFO:Checking exceptions
2022-07-19 23:35:14,313:INFO:Importing libraries
2022-07-19 23:35:14,313:INFO:Copying training dataset
2022-07-19 23:35:14,314:INFO:Defining folds
2022-07-19 23:35:14,314:INFO:Declaring metric variables
2022-07-19 23:35:14,318:INFO:Importing untrained model
2022-07-19 23:35:14,323:INFO:Passive Aggressive Regressor Imported succesfully
2022-07-19 23:35:14,330:INFO:Starting cross validation
2022-07-19 23:35:14,331:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:35:14,396:ERROR:create_model() for par raised an exception:
2022-07-19 23:35:14,396:ERROR:Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2156, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-07-19 23:35:14,396:INFO:Initializing Huber Regressor
2022-07-19 23:35:14,396:INFO:Total runtime is 0.8159741322199504 minutes
2022-07-19 23:35:14,401:INFO:SubProcess create_model() called ==================================
2022-07-19 23:35:14,401:INFO:Initializing create_model()
2022-07-19 23:35:14,401:INFO:create_model(estimator=huber, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:35:14,401:INFO:Checking exceptions
2022-07-19 23:35:14,401:INFO:Importing libraries
2022-07-19 23:35:14,401:INFO:Copying training dataset
2022-07-19 23:35:14,402:INFO:Defining folds
2022-07-19 23:35:14,402:INFO:Declaring metric variables
2022-07-19 23:35:14,406:INFO:Importing untrained model
2022-07-19 23:35:14,410:INFO:Huber Regressor Imported succesfully
2022-07-19 23:35:14,419:INFO:Starting cross validation
2022-07-19 23:35:14,419:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:35:14,576:WARNING:create_model() for huber raised an exception or returned all 0.0, trying without fit_kwargs:
2022-07-19 23:35:14,576:WARNING:Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-07-19 23:35:14,577:INFO:Initializing create_model()
2022-07-19 23:35:14,577:INFO:create_model(estimator=huber, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:35:14,577:INFO:Checking exceptions
2022-07-19 23:35:14,577:INFO:Importing libraries
2022-07-19 23:35:14,577:INFO:Copying training dataset
2022-07-19 23:35:14,578:INFO:Defining folds
2022-07-19 23:35:14,578:INFO:Declaring metric variables
2022-07-19 23:35:14,586:INFO:Importing untrained model
2022-07-19 23:35:14,590:INFO:Huber Regressor Imported succesfully
2022-07-19 23:35:14,598:INFO:Starting cross validation
2022-07-19 23:35:14,598:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:35:14,744:ERROR:create_model() for huber raised an exception:
2022-07-19 23:35:14,744:ERROR:Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2156, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-07-19 23:35:14,744:INFO:Initializing K Neighbors Regressor
2022-07-19 23:35:14,745:INFO:Total runtime is 0.8217761993408204 minutes
2022-07-19 23:35:14,750:INFO:SubProcess create_model() called ==================================
2022-07-19 23:35:14,750:INFO:Initializing create_model()
2022-07-19 23:35:14,750:INFO:create_model(estimator=knn, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:35:14,750:INFO:Checking exceptions
2022-07-19 23:35:14,750:INFO:Importing libraries
2022-07-19 23:35:14,750:INFO:Copying training dataset
2022-07-19 23:35:14,751:INFO:Defining folds
2022-07-19 23:35:14,751:INFO:Declaring metric variables
2022-07-19 23:35:14,755:INFO:Importing untrained model
2022-07-19 23:35:14,764:INFO:K Neighbors Regressor Imported succesfully
2022-07-19 23:35:14,772:INFO:Starting cross validation
2022-07-19 23:35:14,773:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:35:14,847:WARNING:create_model() for knn raised an exception or returned all 0.0, trying without fit_kwargs:
2022-07-19 23:35:14,847:WARNING:Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-07-19 23:35:14,847:INFO:Initializing create_model()
2022-07-19 23:35:14,847:INFO:create_model(estimator=knn, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:35:14,847:INFO:Checking exceptions
2022-07-19 23:35:14,847:INFO:Importing libraries
2022-07-19 23:35:14,847:INFO:Copying training dataset
2022-07-19 23:35:14,848:INFO:Defining folds
2022-07-19 23:35:14,848:INFO:Declaring metric variables
2022-07-19 23:35:14,853:INFO:Importing untrained model
2022-07-19 23:35:14,858:INFO:K Neighbors Regressor Imported succesfully
2022-07-19 23:35:14,866:INFO:Starting cross validation
2022-07-19 23:35:14,866:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:35:14,918:ERROR:create_model() for knn raised an exception:
2022-07-19 23:35:14,918:ERROR:Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2156, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-07-19 23:35:14,919:INFO:Initializing Decision Tree Regressor
2022-07-19 23:35:14,919:INFO:Total runtime is 0.8246766527493795 minutes
2022-07-19 23:35:14,924:INFO:SubProcess create_model() called ==================================
2022-07-19 23:35:14,924:INFO:Initializing create_model()
2022-07-19 23:35:14,924:INFO:create_model(estimator=dt, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:35:14,924:INFO:Checking exceptions
2022-07-19 23:35:14,924:INFO:Importing libraries
2022-07-19 23:35:14,924:INFO:Copying training dataset
2022-07-19 23:35:14,924:INFO:Defining folds
2022-07-19 23:35:14,925:INFO:Declaring metric variables
2022-07-19 23:35:14,929:INFO:Importing untrained model
2022-07-19 23:35:14,935:INFO:Decision Tree Regressor Imported succesfully
2022-07-19 23:35:14,943:INFO:Starting cross validation
2022-07-19 23:35:14,944:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:35:15,005:WARNING:create_model() for dt raised an exception or returned all 0.0, trying without fit_kwargs:
2022-07-19 23:35:15,006:WARNING:Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-07-19 23:35:15,006:INFO:Initializing create_model()
2022-07-19 23:35:15,006:INFO:create_model(estimator=dt, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:35:15,006:INFO:Checking exceptions
2022-07-19 23:35:15,006:INFO:Importing libraries
2022-07-19 23:35:15,006:INFO:Copying training dataset
2022-07-19 23:35:15,007:INFO:Defining folds
2022-07-19 23:35:15,007:INFO:Declaring metric variables
2022-07-19 23:35:15,013:INFO:Importing untrained model
2022-07-19 23:35:15,018:INFO:Decision Tree Regressor Imported succesfully
2022-07-19 23:35:15,026:INFO:Starting cross validation
2022-07-19 23:35:15,026:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:35:15,086:ERROR:create_model() for dt raised an exception:
2022-07-19 23:35:15,086:ERROR:Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2156, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-07-19 23:35:15,086:INFO:Initializing Random Forest Regressor
2022-07-19 23:35:15,086:INFO:Total runtime is 0.8274727662404379 minutes
2022-07-19 23:35:15,091:INFO:SubProcess create_model() called ==================================
2022-07-19 23:35:15,092:INFO:Initializing create_model()
2022-07-19 23:35:15,092:INFO:create_model(estimator=rf, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:35:15,092:INFO:Checking exceptions
2022-07-19 23:35:15,092:INFO:Importing libraries
2022-07-19 23:35:15,092:INFO:Copying training dataset
2022-07-19 23:35:15,093:INFO:Defining folds
2022-07-19 23:35:15,093:INFO:Declaring metric variables
2022-07-19 23:35:15,097:INFO:Importing untrained model
2022-07-19 23:35:15,101:INFO:Random Forest Regressor Imported succesfully
2022-07-19 23:35:15,109:INFO:Starting cross validation
2022-07-19 23:35:15,113:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:35:15,149:WARNING:create_model() for rf raised an exception or returned all 0.0, trying without fit_kwargs:
2022-07-19 23:35:15,149:WARNING:Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-07-19 23:35:15,149:INFO:Initializing create_model()
2022-07-19 23:35:15,149:INFO:create_model(estimator=rf, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:35:15,149:INFO:Checking exceptions
2022-07-19 23:35:15,149:INFO:Importing libraries
2022-07-19 23:35:15,149:INFO:Copying training dataset
2022-07-19 23:35:15,150:INFO:Defining folds
2022-07-19 23:35:15,150:INFO:Declaring metric variables
2022-07-19 23:35:15,154:INFO:Importing untrained model
2022-07-19 23:35:15,159:INFO:Random Forest Regressor Imported succesfully
2022-07-19 23:35:15,170:INFO:Starting cross validation
2022-07-19 23:35:15,170:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:35:15,212:ERROR:create_model() for rf raised an exception:
2022-07-19 23:35:15,212:ERROR:Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2156, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-07-19 23:35:15,213:INFO:Initializing Extra Trees Regressor
2022-07-19 23:35:15,213:INFO:Total runtime is 0.8295777996381124 minutes
2022-07-19 23:35:15,242:INFO:SubProcess create_model() called ==================================
2022-07-19 23:35:15,243:INFO:Initializing create_model()
2022-07-19 23:35:15,243:INFO:create_model(estimator=et, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:35:15,243:INFO:Checking exceptions
2022-07-19 23:35:15,243:INFO:Importing libraries
2022-07-19 23:35:15,243:INFO:Copying training dataset
2022-07-19 23:35:15,244:INFO:Defining folds
2022-07-19 23:35:15,244:INFO:Declaring metric variables
2022-07-19 23:35:15,247:INFO:Importing untrained model
2022-07-19 23:35:15,252:INFO:Extra Trees Regressor Imported succesfully
2022-07-19 23:35:15,260:INFO:Starting cross validation
2022-07-19 23:35:15,261:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:35:15,294:WARNING:create_model() for et raised an exception or returned all 0.0, trying without fit_kwargs:
2022-07-19 23:35:15,294:WARNING:Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-07-19 23:35:15,295:INFO:Initializing create_model()
2022-07-19 23:35:15,295:INFO:create_model(estimator=et, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:35:15,295:INFO:Checking exceptions
2022-07-19 23:35:15,295:INFO:Importing libraries
2022-07-19 23:35:15,295:INFO:Copying training dataset
2022-07-19 23:35:15,295:INFO:Defining folds
2022-07-19 23:35:15,296:INFO:Declaring metric variables
2022-07-19 23:35:15,300:INFO:Importing untrained model
2022-07-19 23:35:15,304:INFO:Extra Trees Regressor Imported succesfully
2022-07-19 23:35:15,314:INFO:Starting cross validation
2022-07-19 23:35:15,315:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:35:15,354:ERROR:create_model() for et raised an exception:
2022-07-19 23:35:15,354:ERROR:Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2156, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-07-19 23:35:15,354:INFO:Initializing AdaBoost Regressor
2022-07-19 23:35:15,354:INFO:Total runtime is 0.8319339315096538 minutes
2022-07-19 23:35:15,359:INFO:SubProcess create_model() called ==================================
2022-07-19 23:35:15,360:INFO:Initializing create_model()
2022-07-19 23:35:15,360:INFO:create_model(estimator=ada, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:35:15,360:INFO:Checking exceptions
2022-07-19 23:35:15,360:INFO:Importing libraries
2022-07-19 23:35:15,360:INFO:Copying training dataset
2022-07-19 23:35:15,361:INFO:Defining folds
2022-07-19 23:35:15,361:INFO:Declaring metric variables
2022-07-19 23:35:15,365:INFO:Importing untrained model
2022-07-19 23:35:15,372:INFO:AdaBoost Regressor Imported succesfully
2022-07-19 23:35:15,381:INFO:Starting cross validation
2022-07-19 23:35:15,381:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:35:15,533:WARNING:create_model() for ada raised an exception or returned all 0.0, trying without fit_kwargs:
2022-07-19 23:35:15,534:WARNING:Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-07-19 23:35:15,534:INFO:Initializing create_model()
2022-07-19 23:35:15,534:INFO:create_model(estimator=ada, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:35:15,534:INFO:Checking exceptions
2022-07-19 23:35:15,534:INFO:Importing libraries
2022-07-19 23:35:15,534:INFO:Copying training dataset
2022-07-19 23:35:15,534:INFO:Defining folds
2022-07-19 23:35:15,535:INFO:Declaring metric variables
2022-07-19 23:35:15,539:INFO:Importing untrained model
2022-07-19 23:35:15,543:INFO:AdaBoost Regressor Imported succesfully
2022-07-19 23:35:15,552:INFO:Starting cross validation
2022-07-19 23:35:15,552:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:35:15,674:ERROR:create_model() for ada raised an exception:
2022-07-19 23:35:15,675:ERROR:Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2156, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-07-19 23:35:15,675:INFO:Initializing Gradient Boosting Regressor
2022-07-19 23:35:15,675:INFO:Total runtime is 0.8372792482376099 minutes
2022-07-19 23:35:15,680:INFO:SubProcess create_model() called ==================================
2022-07-19 23:35:15,681:INFO:Initializing create_model()
2022-07-19 23:35:15,681:INFO:create_model(estimator=gbr, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:35:15,681:INFO:Checking exceptions
2022-07-19 23:35:15,681:INFO:Importing libraries
2022-07-19 23:35:15,681:INFO:Copying training dataset
2022-07-19 23:35:15,681:INFO:Defining folds
2022-07-19 23:35:15,682:INFO:Declaring metric variables
2022-07-19 23:35:15,686:INFO:Importing untrained model
2022-07-19 23:35:15,691:INFO:Gradient Boosting Regressor Imported succesfully
2022-07-19 23:35:15,699:INFO:Starting cross validation
2022-07-19 23:35:15,699:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:35:16,256:WARNING:create_model() for gbr raised an exception or returned all 0.0, trying without fit_kwargs:
2022-07-19 23:35:16,263:WARNING:Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-07-19 23:35:16,263:INFO:Initializing create_model()
2022-07-19 23:35:16,263:INFO:create_model(estimator=gbr, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:35:16,263:INFO:Checking exceptions
2022-07-19 23:35:16,263:INFO:Importing libraries
2022-07-19 23:35:16,263:INFO:Copying training dataset
2022-07-19 23:35:16,264:INFO:Defining folds
2022-07-19 23:35:16,264:INFO:Declaring metric variables
2022-07-19 23:35:16,268:INFO:Importing untrained model
2022-07-19 23:35:16,273:INFO:Gradient Boosting Regressor Imported succesfully
2022-07-19 23:35:16,281:INFO:Starting cross validation
2022-07-19 23:35:16,281:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:35:16,947:ERROR:create_model() for gbr raised an exception:
2022-07-19 23:35:16,947:ERROR:Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2156, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-07-19 23:35:16,947:INFO:Initializing Extreme Gradient Boosting
2022-07-19 23:35:16,947:INFO:Total runtime is 0.8584859013557434 minutes
2022-07-19 23:35:16,952:INFO:SubProcess create_model() called ==================================
2022-07-19 23:35:16,952:INFO:Initializing create_model()
2022-07-19 23:35:16,952:INFO:create_model(estimator=xgboost, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:35:16,953:INFO:Checking exceptions
2022-07-19 23:35:16,953:INFO:Importing libraries
2022-07-19 23:35:16,953:INFO:Copying training dataset
2022-07-19 23:35:16,953:INFO:Defining folds
2022-07-19 23:35:16,953:INFO:Declaring metric variables
2022-07-19 23:35:16,957:INFO:Importing untrained model
2022-07-19 23:35:16,962:INFO:Extreme Gradient Boosting Imported succesfully
2022-07-19 23:35:16,971:INFO:Starting cross validation
2022-07-19 23:35:16,972:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:35:17,197:WARNING:create_model() for xgboost raised an exception or returned all 0.0, trying without fit_kwargs:
2022-07-19 23:35:17,198:WARNING:Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 242, in cross_validate
    See Also
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/parallel.py", line 1056, in __call__
    self.retrieve()
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGSEGV(-11)}

2022-07-19 23:35:17,198:INFO:Initializing create_model()
2022-07-19 23:35:17,198:INFO:create_model(estimator=xgboost, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:35:17,198:INFO:Checking exceptions
2022-07-19 23:35:17,198:INFO:Importing libraries
2022-07-19 23:35:17,198:INFO:Copying training dataset
2022-07-19 23:35:17,199:INFO:Defining folds
2022-07-19 23:35:17,199:INFO:Declaring metric variables
2022-07-19 23:35:17,204:INFO:Importing untrained model
2022-07-19 23:35:17,209:INFO:Extreme Gradient Boosting Imported succesfully
2022-07-19 23:35:17,218:INFO:Starting cross validation
2022-07-19 23:35:17,219:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:35:20,296:ERROR:create_model() for xgboost raised an exception:
2022-07-19 23:35:20,297:ERROR:Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 242, in cross_validate
    See Also
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/parallel.py", line 1056, in __call__
    self.retrieve()
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGSEGV(-11)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2156, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 242, in cross_validate
    See Also
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/parallel.py", line 1056, in __call__
    self.retrieve()
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGSEGV(-11)}

2022-07-19 23:35:20,297:INFO:Initializing Light Gradient Boosting Machine
2022-07-19 23:35:20,297:INFO:Total runtime is 0.9143135825792948 minutes
2022-07-19 23:35:20,305:INFO:SubProcess create_model() called ==================================
2022-07-19 23:35:20,305:INFO:Initializing create_model()
2022-07-19 23:35:20,305:INFO:create_model(estimator=lightgbm, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:35:20,305:INFO:Checking exceptions
2022-07-19 23:35:20,306:INFO:Importing libraries
2022-07-19 23:35:20,306:INFO:Copying training dataset
2022-07-19 23:35:20,307:INFO:Defining folds
2022-07-19 23:35:20,307:INFO:Declaring metric variables
2022-07-19 23:35:20,312:INFO:Importing untrained model
2022-07-19 23:35:20,317:INFO:Light Gradient Boosting Machine Imported succesfully
2022-07-19 23:35:20,325:INFO:Starting cross validation
2022-07-19 23:35:20,326:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:35:23,062:WARNING:create_model() for lightgbm raised an exception or returned all 0.0, trying without fit_kwargs:
2022-07-19 23:35:23,063:WARNING:joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 407, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'lightgbm'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 242, in cross_validate
    See Also
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/parallel.py", line 1056, in __call__
    self.retrieve()
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

2022-07-19 23:35:23,063:INFO:Initializing create_model()
2022-07-19 23:35:23,063:INFO:create_model(estimator=lightgbm, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:35:23,063:INFO:Checking exceptions
2022-07-19 23:35:23,063:INFO:Importing libraries
2022-07-19 23:35:23,063:INFO:Copying training dataset
2022-07-19 23:35:23,065:INFO:Defining folds
2022-07-19 23:35:23,065:INFO:Declaring metric variables
2022-07-19 23:35:23,070:INFO:Importing untrained model
2022-07-19 23:35:23,075:INFO:Light Gradient Boosting Machine Imported succesfully
2022-07-19 23:35:23,084:INFO:Starting cross validation
2022-07-19 23:35:23,085:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:35:25,734:ERROR:create_model() for lightgbm raised an exception:
2022-07-19 23:35:25,735:ERROR:joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 407, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'lightgbm'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2156, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 242, in cross_validate
    See Also
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/parallel.py", line 1056, in __call__
    self.retrieve()
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

2022-07-19 23:35:25,735:INFO:Initializing CatBoost Regressor
2022-07-19 23:35:25,735:INFO:Total runtime is 1.0049463987350464 minutes
2022-07-19 23:35:25,741:INFO:SubProcess create_model() called ==================================
2022-07-19 23:35:25,742:INFO:Initializing create_model()
2022-07-19 23:35:25,742:INFO:create_model(estimator=catboost, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:35:25,742:INFO:Checking exceptions
2022-07-19 23:35:25,742:INFO:Importing libraries
2022-07-19 23:35:25,742:INFO:Copying training dataset
2022-07-19 23:35:25,743:INFO:Defining folds
2022-07-19 23:35:25,743:INFO:Declaring metric variables
2022-07-19 23:35:25,747:INFO:Importing untrained model
2022-07-19 23:35:25,753:INFO:CatBoost Regressor Imported succesfully
2022-07-19 23:35:25,763:INFO:Starting cross validation
2022-07-19 23:35:25,766:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:35:33,922:WARNING:create_model() for catboost raised an exception or returned all 0.0, trying without fit_kwargs:
2022-07-19 23:35:33,923:WARNING:Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-07-19 23:35:33,923:INFO:Initializing create_model()
2022-07-19 23:35:33,923:INFO:create_model(estimator=catboost, fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, display=<pycaret.internal.Display.Display object at 0x7fdba00357c0>, kwargs={})
2022-07-19 23:35:33,923:INFO:Checking exceptions
2022-07-19 23:35:33,923:INFO:Importing libraries
2022-07-19 23:35:33,923:INFO:Copying training dataset
2022-07-19 23:35:33,925:INFO:Defining folds
2022-07-19 23:35:33,925:INFO:Declaring metric variables
2022-07-19 23:35:33,931:INFO:Importing untrained model
2022-07-19 23:35:33,935:INFO:CatBoost Regressor Imported succesfully
2022-07-19 23:35:33,944:INFO:Starting cross validation
2022-07-19 23:35:33,945:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:35:38,355:ERROR:create_model() for catboost raised an exception:
2022-07-19 23:35:38,356:ERROR:Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2136, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2156, in compare_models
    model, model_fit_time = create_model_supervised(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3085, in create_model_supervised
    scores = cross_validate(
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "/Users/kouki/opt/anaconda3/envs/pycaret/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-07-19 23:35:38,367:INFO:Initializing create_model()
2022-07-19 23:35:38,367:INFO:create_model(estimator=Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=4476, solver='auto', tol=0.001), fold=KFold(n_splits=10, random_state=4476, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, verbose=False, system=False, metrics=None, display=None, kwargs={})
2022-07-19 23:35:38,367:INFO:Checking exceptions
2022-07-19 23:35:38,368:INFO:Importing libraries
2022-07-19 23:35:38,368:INFO:Copying training dataset
2022-07-19 23:35:38,368:INFO:Defining folds
2022-07-19 23:35:38,368:INFO:Declaring metric variables
2022-07-19 23:35:38,368:INFO:Importing untrained model
2022-07-19 23:35:38,368:INFO:Declaring custom model
2022-07-19 23:35:38,368:INFO:Ridge Regression Imported succesfully
2022-07-19 23:35:38,368:INFO:Cross validation set to False
2022-07-19 23:35:38,369:INFO:Fitting Model
2022-07-19 23:35:38,377:INFO:Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=4476, solver='auto', tol=0.001)
2022-07-19 23:35:38,377:INFO:create_models() succesfully completed......................................
2022-07-19 23:35:38,531:INFO:create_model_container: 4
2022-07-19 23:35:38,531:INFO:master_model_container: 4
2022-07-19 23:35:38,531:INFO:display_container: 1
2022-07-19 23:35:38,532:INFO:Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=4476, solver='auto', tol=0.001)
2022-07-19 23:35:38,532:INFO:compare_models() succesfully completed......................................
2022-07-19 23:36:05,278:INFO:Initializing create_model()
2022-07-19 23:36:05,281:INFO:create_model(estimator=ridge, fold=None, round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=True, verbose=True, system=True, metrics=None, display=None, kwargs={})
2022-07-19 23:36:05,281:INFO:Checking exceptions
2022-07-19 23:36:05,286:INFO:Preparing display monitor
2022-07-19 23:36:05,322:INFO:Importing libraries
2022-07-19 23:36:05,324:INFO:Copying training dataset
2022-07-19 23:36:05,325:INFO:Defining folds
2022-07-19 23:36:05,325:INFO:Declaring metric variables
2022-07-19 23:36:05,333:INFO:Importing untrained model
2022-07-19 23:36:05,340:INFO:Ridge Regression Imported succesfully
2022-07-19 23:36:05,354:INFO:Starting cross validation
2022-07-19 23:36:05,355:INFO:Cross validating with KFold(n_splits=10, random_state=4476, shuffle=False), n_jobs=-1
2022-07-19 23:38:05,964:INFO:PyCaret Supervised Module
2022-07-19 23:38:05,964:INFO:ML Usecase: classification
2022-07-19 23:38:05,965:INFO:version 2.2.2
2022-07-19 23:38:05,965:INFO:Initializing setup()
2022-07-19 23:38:05,965:INFO:setup(target=Attrition, ml_usecase=classification, available_plots={'parameter': 'Hyperparameters', 'auc': 'AUC', 'confusion_matrix': 'Confusion Matrix', 'threshold': 'Threshold', 'pr': 'Precision Recall', 'error': 'Prediction Error', 'class_report': 'Class Report', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'calibration': 'Calibration Curve', 'vc': 'Validation Curve', 'dimension': 'Dimensions', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'boundary': 'Decision Boundary', 'lift': 'Lift Chart', 'gain': 'Gain Chart', 'tree': 'Decision Tree'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=stratifiedkfold, fold=10, fold_shuffle=False, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=None, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2022-07-19 23:38:05,965:INFO:Checking environment
2022-07-19 23:38:05,965:INFO:python_version: 3.9.7
2022-07-19 23:38:05,965:INFO:python_build: ('default', 'Sep 16 2021 08:50:36')
2022-07-19 23:38:05,967:INFO:machine: x86_64
2022-07-19 23:38:05,967:INFO:platform: macOS-10.16-x86_64-i386-64bit
2022-07-19 23:38:05,967:INFO:Memory: svmem(total=17179869184, available=917123072, percent=94.7, used=1315061760, free=123162624, active=797130752, inactive=777699328, wired=517931008)
2022-07-19 23:38:05,967:INFO:Physical Core: 8
2022-07-19 23:38:05,968:INFO:Logical Core: 8
2022-07-19 23:38:05,968:INFO:Checking libraries
2022-07-19 23:38:05,968:INFO:pd==1.4.2
2022-07-19 23:38:05,970:INFO:numpy==1.21.5
2022-07-19 23:38:05,970:INFO:sklearn==0.23.2
2022-07-19 23:38:05,970:INFO:xgboost==1.5.2
2022-07-19 23:38:05,970:INFO:lightgbm==3.3.2
2022-07-19 23:38:05,971:INFO:catboost==1.0.4
2022-07-19 23:38:05,971:INFO:mlflow==1.24.0
2022-07-19 23:38:05,971:INFO:Checking Exceptions
2022-07-19 23:38:05,971:INFO:Declaring global variables
2022-07-19 23:38:05,971:INFO:USI: bec9
2022-07-19 23:38:05,971:INFO:pycaret_globals: {'_all_models_internal', 'fold_param', 'y_train', 'imputation_classifier', 'fix_imbalance_param', 'target_param', 'n_jobs_param', 'y_test', 'gpu_param', 'log_plots_param', 'prep_pipe', 'imputation_regressor', 'logging_param', 'exp_name_log', 'seed', '_ml_usecase', 'fold_generator', 'master_model_container', 'pycaret_globals', 'stratify_param', 'X_train', 'fold_shuffle_param', 'y', 'display_container', 'create_model_container', 'data_before_preprocess', '_all_metrics', 'X', 'X_test', 'experiment__', 'fix_imbalance_method_param', '_available_plots', 'iterative_imputation_iters_param', 'transform_target_param', 'transform_target_method_param', 'USI', 'html_param', 'fold_groups_param', '_all_models', '_internal_pipeline', '_gpu_n_jobs_param'}
2022-07-19 23:38:05,971:INFO:Preparing display monitor
2022-07-19 23:38:05,971:INFO:Preparing display monitor
2022-07-19 23:38:05,983:INFO:Importing libraries
2022-07-19 23:38:05,984:INFO:Copying data for preprocessing
2022-07-19 23:38:05,988:INFO:Declaring preprocessing parameters
2022-07-19 23:38:05,989:INFO:Creating preprocessing pipeline
2022-07-19 23:38:05,998:INFO:Preprocessing pipeline created successfully
2022-07-19 23:38:05,999:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2022-07-19 23:38:05,999:INFO:Creating global containers
2022-07-19 23:38:05,999:INFO:Internal pipeline: Pipeline(memory=None, steps=[('empty_step', 'passthrough')], verbose=False)
2022-07-19 23:43:17,357:INFO:PyCaret Supervised Module
2022-07-19 23:43:17,358:INFO:ML Usecase: classification
2022-07-19 23:43:17,366:INFO:version 2.2.2
2022-07-19 23:43:17,366:INFO:Initializing setup()
2022-07-19 23:43:17,366:INFO:setup(target=Attrition, ml_usecase=classification, available_plots={'parameter': 'Hyperparameters', 'auc': 'AUC', 'confusion_matrix': 'Confusion Matrix', 'threshold': 'Threshold', 'pr': 'Precision Recall', 'error': 'Prediction Error', 'class_report': 'Class Report', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'calibration': 'Calibration Curve', 'vc': 'Validation Curve', 'dimension': 'Dimensions', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'boundary': 'Decision Boundary', 'lift': 'Lift Chart', 'gain': 'Gain Chart', 'tree': 'Decision Tree'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=stratifiedkfold, fold=10, fold_shuffle=False, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=None, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2022-07-19 23:43:17,366:INFO:Checking environment
2022-07-19 23:43:17,367:INFO:python_version: 3.9.7
2022-07-19 23:43:17,367:INFO:python_build: ('default', 'Sep 16 2021 08:50:36')
2022-07-19 23:43:17,367:INFO:machine: x86_64
2022-07-19 23:43:17,367:INFO:platform: macOS-10.16-x86_64-i386-64bit
2022-07-19 23:43:17,367:INFO:Memory: svmem(total=17179869184, available=821399552, percent=95.2, used=1342513152, free=18186240, active=806649856, inactive=793944064, wired=535863296)
2022-07-19 23:43:17,367:INFO:Physical Core: 8
2022-07-19 23:43:17,367:INFO:Logical Core: 8
2022-07-19 23:43:17,367:INFO:Checking libraries
2022-07-19 23:43:17,367:INFO:pd==1.4.2
2022-07-19 23:43:17,368:INFO:numpy==1.21.5
2022-07-19 23:43:17,368:INFO:sklearn==0.23.2
2022-07-19 23:43:17,368:INFO:xgboost==1.5.2
2022-07-19 23:43:17,368:INFO:lightgbm==3.3.2
2022-07-19 23:43:17,368:INFO:catboost==1.0.4
2022-07-19 23:43:17,368:INFO:mlflow==1.24.0
2022-07-19 23:43:17,368:INFO:Checking Exceptions
2022-07-19 23:43:17,368:INFO:Declaring global variables
2022-07-19 23:43:17,368:INFO:USI: 0acf
2022-07-19 23:43:17,368:INFO:pycaret_globals: {'_all_models_internal', 'fold_param', 'y_train', 'imputation_classifier', 'fix_imbalance_param', 'target_param', 'n_jobs_param', 'y_test', 'gpu_param', 'log_plots_param', 'prep_pipe', 'imputation_regressor', 'logging_param', 'exp_name_log', 'seed', '_ml_usecase', 'fold_generator', 'master_model_container', 'pycaret_globals', 'stratify_param', 'X_train', 'fold_shuffle_param', 'y', 'display_container', 'create_model_container', 'data_before_preprocess', '_all_metrics', 'X', 'X_test', 'experiment__', 'fix_imbalance_method_param', '_available_plots', 'iterative_imputation_iters_param', 'transform_target_param', 'transform_target_method_param', 'USI', 'html_param', 'fold_groups_param', '_all_models', '_internal_pipeline', '_gpu_n_jobs_param'}
2022-07-19 23:43:17,369:INFO:Preparing display monitor
2022-07-19 23:43:17,369:INFO:Preparing display monitor
2022-07-19 23:43:17,381:INFO:Importing libraries
2022-07-19 23:43:17,381:INFO:Copying data for preprocessing
2022-07-19 23:43:17,385:INFO:Declaring preprocessing parameters
2022-07-19 23:43:17,386:INFO:Creating preprocessing pipeline
2022-07-19 23:43:17,395:INFO:Preprocessing pipeline created successfully
2022-07-19 23:43:17,395:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2022-07-19 23:43:17,396:INFO:Creating global containers
2022-07-19 23:43:17,396:INFO:Internal pipeline: Pipeline(memory=None, steps=[('empty_step', 'passthrough')], verbose=False)
2022-07-19 23:52:38,784:INFO:PyCaret Supervised Module
2022-07-19 23:52:38,785:INFO:ML Usecase: classification
2022-07-19 23:52:38,786:INFO:version 2.2.2
2022-07-19 23:52:38,786:INFO:Initializing setup()
2022-07-19 23:52:38,786:INFO:setup(target=Attrition, ml_usecase=classification, available_plots={'parameter': 'Hyperparameters', 'auc': 'AUC', 'confusion_matrix': 'Confusion Matrix', 'threshold': 'Threshold', 'pr': 'Precision Recall', 'error': 'Prediction Error', 'class_report': 'Class Report', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'calibration': 'Calibration Curve', 'vc': 'Validation Curve', 'dimension': 'Dimensions', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'boundary': 'Decision Boundary', 'lift': 'Lift Chart', 'gain': 'Gain Chart', 'tree': 'Decision Tree'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=stratifiedkfold, fold=10, fold_shuffle=False, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=None, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2022-07-19 23:52:38,786:INFO:Checking environment
2022-07-19 23:52:38,790:INFO:python_version: 3.9.7
2022-07-19 23:52:38,790:INFO:python_build: ('default', 'Sep 16 2021 08:50:36')
2022-07-19 23:52:38,790:INFO:machine: x86_64
2022-07-19 23:52:38,790:INFO:platform: macOS-10.16-x86_64-i386-64bit
2022-07-19 23:52:38,791:INFO:Memory: svmem(total=17179869184, available=799490048, percent=95.3, used=1319731200, free=14753792, active=789401600, inactive=741761024, wired=530329600)
2022-07-19 23:52:38,792:INFO:Physical Core: 8
2022-07-19 23:52:38,792:INFO:Logical Core: 8
2022-07-19 23:52:38,792:INFO:Checking libraries
2022-07-19 23:52:38,792:INFO:pd==1.4.2
2022-07-19 23:52:38,792:INFO:numpy==1.21.5
2022-07-19 23:52:38,792:INFO:sklearn==1.0.2
2022-07-19 23:52:38,859:INFO:xgboost==1.5.2
2022-07-19 23:52:38,859:INFO:lightgbm==3.3.2
2022-07-19 23:52:38,911:INFO:catboost==1.0.4
2022-07-19 23:52:39,067:WARNING:mlflow not found
2022-07-19 23:52:39,067:INFO:Checking Exceptions
2022-07-19 23:52:39,067:INFO:Declaring global variables
2022-07-19 23:52:39,067:INFO:USI: fa0e
2022-07-19 23:52:39,067:INFO:pycaret_globals: {'fix_imbalance_param', 'prep_pipe', 'X_train', 'stratify_param', 'y_test', 'target_param', 'seed', 'master_model_container', 'y_train', 'experiment__', '_available_plots', 'iterative_imputation_iters_param', 'X', 'X_test', 'log_plots_param', '_internal_pipeline', 'data_before_preprocess', 'n_jobs_param', 'fix_imbalance_method_param', 'display_container', 'transform_target_method_param', 'gpu_param', 'html_param', '_all_models_internal', '_ml_usecase', '_gpu_n_jobs_param', 'fold_param', 'imputation_regressor', 'imputation_classifier', 'exp_name_log', 'transform_target_param', 'fold_groups_param', 'fold_generator', 'USI', 'fold_shuffle_param', '_all_models', 'logging_param', '_all_metrics', 'pycaret_globals', 'create_model_container', 'y'}
2022-07-19 23:52:39,067:INFO:Preparing display monitor
2022-07-19 23:52:39,067:INFO:Preparing display monitor
2022-07-19 23:52:39,075:INFO:Importing libraries
2022-07-19 23:52:39,075:INFO:Copying data for preprocessing
2022-07-19 23:52:39,080:INFO:Declaring preprocessing parameters
2022-07-19 23:52:39,084:INFO:Creating preprocessing pipeline
2022-07-19 23:52:39,095:INFO:Preprocessing pipeline created successfully
2022-07-19 23:52:39,095:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2022-07-19 23:52:39,095:INFO:Creating global containers
2022-07-19 23:54:01,707:INFO:PyCaret Supervised Module
2022-07-19 23:54:01,708:INFO:ML Usecase: classification
2022-07-19 23:54:01,708:INFO:version 2.2.2
2022-07-19 23:54:01,709:INFO:Initializing setup()
2022-07-19 23:54:01,709:INFO:setup(target=Attrition, ml_usecase=classification, available_plots={'parameter': 'Hyperparameters', 'auc': 'AUC', 'confusion_matrix': 'Confusion Matrix', 'threshold': 'Threshold', 'pr': 'Precision Recall', 'error': 'Prediction Error', 'class_report': 'Class Report', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'calibration': 'Calibration Curve', 'vc': 'Validation Curve', 'dimension': 'Dimensions', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'boundary': 'Decision Boundary', 'lift': 'Lift Chart', 'gain': 'Gain Chart', 'tree': 'Decision Tree'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=stratifiedkfold, fold=10, fold_shuffle=True, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=None, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2022-07-19 23:54:01,709:INFO:Checking environment
2022-07-19 23:54:01,709:INFO:python_version: 3.9.7
2022-07-19 23:54:01,709:INFO:python_build: ('default', 'Sep 16 2021 08:50:36')
2022-07-19 23:54:01,709:INFO:machine: x86_64
2022-07-19 23:54:01,709:INFO:platform: macOS-10.16-x86_64-i386-64bit
2022-07-19 23:54:01,710:INFO:Memory: svmem(total=17179869184, available=839499776, percent=95.1, used=1344598016, free=19935232, active=823472128, inactive=786952192, wired=521125888)
2022-07-19 23:54:01,710:INFO:Physical Core: 8
2022-07-19 23:54:01,710:INFO:Logical Core: 8
2022-07-19 23:54:01,710:INFO:Checking libraries
2022-07-19 23:54:01,710:INFO:pd==1.4.2
2022-07-19 23:54:01,710:INFO:numpy==1.21.5
2022-07-19 23:54:01,710:INFO:sklearn==1.0.2
2022-07-19 23:54:01,710:INFO:xgboost==1.5.2
2022-07-19 23:54:01,710:INFO:lightgbm==3.3.2
2022-07-19 23:54:01,710:INFO:catboost==1.0.4
2022-07-19 23:54:01,710:INFO:mlflow==1.24.0
2022-07-19 23:54:01,710:INFO:Checking Exceptions
2022-07-19 23:54:01,711:INFO:Declaring global variables
2022-07-19 23:54:01,712:INFO:USI: 58ac
2022-07-19 23:54:01,713:INFO:pycaret_globals: {'fix_imbalance_param', 'prep_pipe', 'X_train', 'stratify_param', 'y_test', 'target_param', 'seed', 'master_model_container', 'y_train', 'experiment__', '_available_plots', 'iterative_imputation_iters_param', 'X', 'X_test', 'log_plots_param', '_internal_pipeline', 'data_before_preprocess', 'n_jobs_param', 'fix_imbalance_method_param', 'display_container', 'transform_target_method_param', 'gpu_param', 'html_param', '_all_models_internal', '_ml_usecase', '_gpu_n_jobs_param', 'fold_param', 'imputation_regressor', 'imputation_classifier', 'exp_name_log', 'transform_target_param', 'fold_groups_param', 'fold_generator', 'USI', 'fold_shuffle_param', '_all_models', 'logging_param', '_all_metrics', 'pycaret_globals', 'create_model_container', 'y'}
2022-07-19 23:54:01,713:INFO:Preparing display monitor
2022-07-19 23:54:01,714:INFO:Preparing display monitor
2022-07-19 23:54:01,730:INFO:Importing libraries
2022-07-19 23:54:01,732:INFO:Copying data for preprocessing
2022-07-19 23:54:01,741:INFO:Declaring preprocessing parameters
2022-07-19 23:54:01,743:INFO:Creating preprocessing pipeline
2022-07-19 23:54:01,759:INFO:Preprocessing pipeline created successfully
2022-07-19 23:54:01,759:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2022-07-19 23:54:01,759:INFO:Creating global containers
2022-07-19 23:54:01,761:INFO:Internal pipeline: Pipeline(memory=None, steps=[('empty_step', 'passthrough')], verbose=False)
2022-07-19 23:54:03,519:INFO:Creating grid variables
2022-07-19 23:54:03,529:INFO:create_model_container: 0
2022-07-19 23:54:03,529:INFO:master_model_container: 0
2022-07-19 23:54:03,529:INFO:display_container: 0
